// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DetailsColumns holds the columns for the "details" table.
	DetailsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "app_id", Type: field.TypeUUID, Nullable: true},
		{Name: "user_id", Type: field.TypeUUID, Nullable: true},
		{Name: "coin_type_id", Type: field.TypeUUID, Nullable: true},
		{Name: "io_type", Type: field.TypeString, Nullable: true, Default: "DefaultType"},
		{Name: "io_sub_type", Type: field.TypeString, Nullable: true, Default: "DefaultSubType"},
		{Name: "amount", Type: field.TypeUint64, Nullable: true, Default: 0},
		{Name: "amount_precision", Type: field.TypeUint32, Nullable: true, Default: 6},
		{Name: "from_coin_type_id", Type: field.TypeUUID, Nullable: true},
		{Name: "coin_usd_currency", Type: field.TypeUint64, Nullable: true, Default: 0},
		{Name: "io_extra", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "from_old_id", Type: field.TypeUUID, Nullable: true},
	}
	// DetailsTable holds the schema information for the "details" table.
	DetailsTable = &schema.Table{
		Name:       "details",
		Columns:    DetailsColumns,
		PrimaryKey: []*schema.Column{DetailsColumns[0]},
	}
	// GeneralsColumns holds the columns for the "generals" table.
	GeneralsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "app_id", Type: field.TypeUUID, Nullable: true},
		{Name: "user_id", Type: field.TypeUUID, Nullable: true},
		{Name: "coin_type_id", Type: field.TypeUUID, Nullable: true},
		{Name: "incoming", Type: field.TypeUint64, Nullable: true, Default: 0},
		{Name: "locked", Type: field.TypeUint64, Nullable: true, Default: 0},
		{Name: "outcoming", Type: field.TypeUint64, Nullable: true, Default: 0},
		{Name: "spendable", Type: field.TypeUint64, Nullable: true, Default: 0},
		{Name: "precision", Type: field.TypeUint32, Nullable: true, Default: 6},
	}
	// GeneralsTable holds the schema information for the "generals" table.
	GeneralsTable = &schema.Table{
		Name:       "generals",
		Columns:    GeneralsColumns,
		PrimaryKey: []*schema.Column{GeneralsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DetailsTable,
		GeneralsTable,
	}
)

func init() {
}
