// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/NpoolPlatform/ledger-manager/pkg/db/ent/detail"
	"github.com/NpoolPlatform/ledger-manager/pkg/db/ent/general"
	"github.com/NpoolPlatform/ledger-manager/pkg/db/ent/miningprofitdetail"
	"github.com/NpoolPlatform/ledger-manager/pkg/db/ent/miningprofitgeneral"
	"github.com/NpoolPlatform/ledger-manager/pkg/db/ent/miningprofitunsold"
	"github.com/NpoolPlatform/ledger-manager/pkg/db/ent/profit"
	"github.com/NpoolPlatform/ledger-manager/pkg/db/ent/withdraw"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 7)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   detail.Table,
			Columns: detail.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: detail.FieldID,
			},
		},
		Type: "Detail",
		Fields: map[string]*sqlgraph.FieldSpec{
			detail.FieldCreatedAt:       {Type: field.TypeUint32, Column: detail.FieldCreatedAt},
			detail.FieldUpdatedAt:       {Type: field.TypeUint32, Column: detail.FieldUpdatedAt},
			detail.FieldDeletedAt:       {Type: field.TypeUint32, Column: detail.FieldDeletedAt},
			detail.FieldAppID:           {Type: field.TypeUUID, Column: detail.FieldAppID},
			detail.FieldUserID:          {Type: field.TypeUUID, Column: detail.FieldUserID},
			detail.FieldCoinTypeID:      {Type: field.TypeUUID, Column: detail.FieldCoinTypeID},
			detail.FieldIoType:          {Type: field.TypeString, Column: detail.FieldIoType},
			detail.FieldIoSubType:       {Type: field.TypeString, Column: detail.FieldIoSubType},
			detail.FieldAmount:          {Type: field.TypeFloat64, Column: detail.FieldAmount},
			detail.FieldFromCoinTypeID:  {Type: field.TypeUUID, Column: detail.FieldFromCoinTypeID},
			detail.FieldCoinUsdCurrency: {Type: field.TypeFloat64, Column: detail.FieldCoinUsdCurrency},
			detail.FieldIoExtra:         {Type: field.TypeString, Column: detail.FieldIoExtra},
		},
	}
	graph.Nodes[1] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   general.Table,
			Columns: general.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: general.FieldID,
			},
		},
		Type: "General",
		Fields: map[string]*sqlgraph.FieldSpec{
			general.FieldCreatedAt:  {Type: field.TypeUint32, Column: general.FieldCreatedAt},
			general.FieldUpdatedAt:  {Type: field.TypeUint32, Column: general.FieldUpdatedAt},
			general.FieldDeletedAt:  {Type: field.TypeUint32, Column: general.FieldDeletedAt},
			general.FieldAppID:      {Type: field.TypeUUID, Column: general.FieldAppID},
			general.FieldUserID:     {Type: field.TypeUUID, Column: general.FieldUserID},
			general.FieldCoinTypeID: {Type: field.TypeUUID, Column: general.FieldCoinTypeID},
			general.FieldIncoming:   {Type: field.TypeFloat64, Column: general.FieldIncoming},
			general.FieldLocked:     {Type: field.TypeFloat64, Column: general.FieldLocked},
			general.FieldOutcoming:  {Type: field.TypeFloat64, Column: general.FieldOutcoming},
			general.FieldSpendable:  {Type: field.TypeFloat64, Column: general.FieldSpendable},
		},
	}
	graph.Nodes[2] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   miningprofitdetail.Table,
			Columns: miningprofitdetail.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: miningprofitdetail.FieldID,
			},
		},
		Type: "MiningProfitDetail",
		Fields: map[string]*sqlgraph.FieldSpec{
			miningprofitdetail.FieldCreatedAt:   {Type: field.TypeUint32, Column: miningprofitdetail.FieldCreatedAt},
			miningprofitdetail.FieldUpdatedAt:   {Type: field.TypeUint32, Column: miningprofitdetail.FieldUpdatedAt},
			miningprofitdetail.FieldDeletedAt:   {Type: field.TypeUint32, Column: miningprofitdetail.FieldDeletedAt},
			miningprofitdetail.FieldGoodID:      {Type: field.TypeUUID, Column: miningprofitdetail.FieldGoodID},
			miningprofitdetail.FieldCoinTypeID:  {Type: field.TypeUUID, Column: miningprofitdetail.FieldCoinTypeID},
			miningprofitdetail.FieldAmount:      {Type: field.TypeFloat64, Column: miningprofitdetail.FieldAmount},
			miningprofitdetail.FieldBenefitDate: {Type: field.TypeUint32, Column: miningprofitdetail.FieldBenefitDate},
		},
	}
	graph.Nodes[3] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   miningprofitgeneral.Table,
			Columns: miningprofitgeneral.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: miningprofitgeneral.FieldID,
			},
		},
		Type: "MiningProfitGeneral",
		Fields: map[string]*sqlgraph.FieldSpec{
			miningprofitgeneral.FieldCreatedAt:  {Type: field.TypeUint32, Column: miningprofitgeneral.FieldCreatedAt},
			miningprofitgeneral.FieldUpdatedAt:  {Type: field.TypeUint32, Column: miningprofitgeneral.FieldUpdatedAt},
			miningprofitgeneral.FieldDeletedAt:  {Type: field.TypeUint32, Column: miningprofitgeneral.FieldDeletedAt},
			miningprofitgeneral.FieldGoodID:     {Type: field.TypeUUID, Column: miningprofitgeneral.FieldGoodID},
			miningprofitgeneral.FieldCoinTypeID: {Type: field.TypeUUID, Column: miningprofitgeneral.FieldCoinTypeID},
			miningprofitgeneral.FieldAmount:     {Type: field.TypeFloat64, Column: miningprofitgeneral.FieldAmount},
			miningprofitgeneral.FieldToPlatform: {Type: field.TypeFloat64, Column: miningprofitgeneral.FieldToPlatform},
			miningprofitgeneral.FieldToUser:     {Type: field.TypeFloat64, Column: miningprofitgeneral.FieldToUser},
		},
	}
	graph.Nodes[4] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   miningprofitunsold.Table,
			Columns: miningprofitunsold.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: miningprofitunsold.FieldID,
			},
		},
		Type: "MiningProfitUnsold",
		Fields: map[string]*sqlgraph.FieldSpec{
			miningprofitunsold.FieldCreatedAt:   {Type: field.TypeUint32, Column: miningprofitunsold.FieldCreatedAt},
			miningprofitunsold.FieldUpdatedAt:   {Type: field.TypeUint32, Column: miningprofitunsold.FieldUpdatedAt},
			miningprofitunsold.FieldDeletedAt:   {Type: field.TypeUint32, Column: miningprofitunsold.FieldDeletedAt},
			miningprofitunsold.FieldGoodID:      {Type: field.TypeUUID, Column: miningprofitunsold.FieldGoodID},
			miningprofitunsold.FieldCoinTypeID:  {Type: field.TypeUUID, Column: miningprofitunsold.FieldCoinTypeID},
			miningprofitunsold.FieldAmount:      {Type: field.TypeFloat64, Column: miningprofitunsold.FieldAmount},
			miningprofitunsold.FieldBenefitDate: {Type: field.TypeUint32, Column: miningprofitunsold.FieldBenefitDate},
		},
	}
	graph.Nodes[5] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   profit.Table,
			Columns: profit.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: profit.FieldID,
			},
		},
		Type: "Profit",
		Fields: map[string]*sqlgraph.FieldSpec{
			profit.FieldCreatedAt:  {Type: field.TypeUint32, Column: profit.FieldCreatedAt},
			profit.FieldUpdatedAt:  {Type: field.TypeUint32, Column: profit.FieldUpdatedAt},
			profit.FieldDeletedAt:  {Type: field.TypeUint32, Column: profit.FieldDeletedAt},
			profit.FieldAppID:      {Type: field.TypeUUID, Column: profit.FieldAppID},
			profit.FieldUserID:     {Type: field.TypeUUID, Column: profit.FieldUserID},
			profit.FieldCoinTypeID: {Type: field.TypeUUID, Column: profit.FieldCoinTypeID},
			profit.FieldIncoming:   {Type: field.TypeFloat64, Column: profit.FieldIncoming},
		},
	}
	graph.Nodes[6] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   withdraw.Table,
			Columns: withdraw.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: withdraw.FieldID,
			},
		},
		Type: "Withdraw",
		Fields: map[string]*sqlgraph.FieldSpec{
			withdraw.FieldCreatedAt:             {Type: field.TypeUint32, Column: withdraw.FieldCreatedAt},
			withdraw.FieldUpdatedAt:             {Type: field.TypeUint32, Column: withdraw.FieldUpdatedAt},
			withdraw.FieldDeletedAt:             {Type: field.TypeUint32, Column: withdraw.FieldDeletedAt},
			withdraw.FieldAppID:                 {Type: field.TypeUUID, Column: withdraw.FieldAppID},
			withdraw.FieldUserID:                {Type: field.TypeUUID, Column: withdraw.FieldUserID},
			withdraw.FieldCoinTypeID:            {Type: field.TypeUUID, Column: withdraw.FieldCoinTypeID},
			withdraw.FieldAccountID:             {Type: field.TypeUUID, Column: withdraw.FieldAccountID},
			withdraw.FieldPlatformTransactionID: {Type: field.TypeUUID, Column: withdraw.FieldPlatformTransactionID},
			withdraw.FieldChainTransactionID:    {Type: field.TypeString, Column: withdraw.FieldChainTransactionID},
			withdraw.FieldState:                 {Type: field.TypeString, Column: withdraw.FieldState},
			withdraw.FieldAmount:                {Type: field.TypeFloat64, Column: withdraw.FieldAmount},
		},
	}
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (dq *DetailQuery) addPredicate(pred func(s *sql.Selector)) {
	dq.predicates = append(dq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the DetailQuery builder.
func (dq *DetailQuery) Filter() *DetailFilter {
	return &DetailFilter{config: dq.config, predicateAdder: dq}
}

// addPredicate implements the predicateAdder interface.
func (m *DetailMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the DetailMutation builder.
func (m *DetailMutation) Filter() *DetailFilter {
	return &DetailFilter{config: m.config, predicateAdder: m}
}

// DetailFilter provides a generic filtering capability at runtime for DetailQuery.
type DetailFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *DetailFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *DetailFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(detail.FieldID))
}

// WhereCreatedAt applies the entql uint32 predicate on the created_at field.
func (f *DetailFilter) WhereCreatedAt(p entql.Uint32P) {
	f.Where(p.Field(detail.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql uint32 predicate on the updated_at field.
func (f *DetailFilter) WhereUpdatedAt(p entql.Uint32P) {
	f.Where(p.Field(detail.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql uint32 predicate on the deleted_at field.
func (f *DetailFilter) WhereDeletedAt(p entql.Uint32P) {
	f.Where(p.Field(detail.FieldDeletedAt))
}

// WhereAppID applies the entql [16]byte predicate on the app_id field.
func (f *DetailFilter) WhereAppID(p entql.ValueP) {
	f.Where(p.Field(detail.FieldAppID))
}

// WhereUserID applies the entql [16]byte predicate on the user_id field.
func (f *DetailFilter) WhereUserID(p entql.ValueP) {
	f.Where(p.Field(detail.FieldUserID))
}

// WhereCoinTypeID applies the entql [16]byte predicate on the coin_type_id field.
func (f *DetailFilter) WhereCoinTypeID(p entql.ValueP) {
	f.Where(p.Field(detail.FieldCoinTypeID))
}

// WhereIoType applies the entql string predicate on the io_type field.
func (f *DetailFilter) WhereIoType(p entql.StringP) {
	f.Where(p.Field(detail.FieldIoType))
}

// WhereIoSubType applies the entql string predicate on the io_sub_type field.
func (f *DetailFilter) WhereIoSubType(p entql.StringP) {
	f.Where(p.Field(detail.FieldIoSubType))
}

// WhereAmount applies the entql float64 predicate on the amount field.
func (f *DetailFilter) WhereAmount(p entql.Float64P) {
	f.Where(p.Field(detail.FieldAmount))
}

// WhereFromCoinTypeID applies the entql [16]byte predicate on the from_coin_type_id field.
func (f *DetailFilter) WhereFromCoinTypeID(p entql.ValueP) {
	f.Where(p.Field(detail.FieldFromCoinTypeID))
}

// WhereCoinUsdCurrency applies the entql float64 predicate on the coin_usd_currency field.
func (f *DetailFilter) WhereCoinUsdCurrency(p entql.Float64P) {
	f.Where(p.Field(detail.FieldCoinUsdCurrency))
}

// WhereIoExtra applies the entql string predicate on the io_extra field.
func (f *DetailFilter) WhereIoExtra(p entql.StringP) {
	f.Where(p.Field(detail.FieldIoExtra))
}

// addPredicate implements the predicateAdder interface.
func (gq *GeneralQuery) addPredicate(pred func(s *sql.Selector)) {
	gq.predicates = append(gq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the GeneralQuery builder.
func (gq *GeneralQuery) Filter() *GeneralFilter {
	return &GeneralFilter{config: gq.config, predicateAdder: gq}
}

// addPredicate implements the predicateAdder interface.
func (m *GeneralMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the GeneralMutation builder.
func (m *GeneralMutation) Filter() *GeneralFilter {
	return &GeneralFilter{config: m.config, predicateAdder: m}
}

// GeneralFilter provides a generic filtering capability at runtime for GeneralQuery.
type GeneralFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *GeneralFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[1].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *GeneralFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(general.FieldID))
}

// WhereCreatedAt applies the entql uint32 predicate on the created_at field.
func (f *GeneralFilter) WhereCreatedAt(p entql.Uint32P) {
	f.Where(p.Field(general.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql uint32 predicate on the updated_at field.
func (f *GeneralFilter) WhereUpdatedAt(p entql.Uint32P) {
	f.Where(p.Field(general.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql uint32 predicate on the deleted_at field.
func (f *GeneralFilter) WhereDeletedAt(p entql.Uint32P) {
	f.Where(p.Field(general.FieldDeletedAt))
}

// WhereAppID applies the entql [16]byte predicate on the app_id field.
func (f *GeneralFilter) WhereAppID(p entql.ValueP) {
	f.Where(p.Field(general.FieldAppID))
}

// WhereUserID applies the entql [16]byte predicate on the user_id field.
func (f *GeneralFilter) WhereUserID(p entql.ValueP) {
	f.Where(p.Field(general.FieldUserID))
}

// WhereCoinTypeID applies the entql [16]byte predicate on the coin_type_id field.
func (f *GeneralFilter) WhereCoinTypeID(p entql.ValueP) {
	f.Where(p.Field(general.FieldCoinTypeID))
}

// WhereIncoming applies the entql float64 predicate on the incoming field.
func (f *GeneralFilter) WhereIncoming(p entql.Float64P) {
	f.Where(p.Field(general.FieldIncoming))
}

// WhereLocked applies the entql float64 predicate on the locked field.
func (f *GeneralFilter) WhereLocked(p entql.Float64P) {
	f.Where(p.Field(general.FieldLocked))
}

// WhereOutcoming applies the entql float64 predicate on the outcoming field.
func (f *GeneralFilter) WhereOutcoming(p entql.Float64P) {
	f.Where(p.Field(general.FieldOutcoming))
}

// WhereSpendable applies the entql float64 predicate on the spendable field.
func (f *GeneralFilter) WhereSpendable(p entql.Float64P) {
	f.Where(p.Field(general.FieldSpendable))
}

// addPredicate implements the predicateAdder interface.
func (mpdq *MiningProfitDetailQuery) addPredicate(pred func(s *sql.Selector)) {
	mpdq.predicates = append(mpdq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the MiningProfitDetailQuery builder.
func (mpdq *MiningProfitDetailQuery) Filter() *MiningProfitDetailFilter {
	return &MiningProfitDetailFilter{config: mpdq.config, predicateAdder: mpdq}
}

// addPredicate implements the predicateAdder interface.
func (m *MiningProfitDetailMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the MiningProfitDetailMutation builder.
func (m *MiningProfitDetailMutation) Filter() *MiningProfitDetailFilter {
	return &MiningProfitDetailFilter{config: m.config, predicateAdder: m}
}

// MiningProfitDetailFilter provides a generic filtering capability at runtime for MiningProfitDetailQuery.
type MiningProfitDetailFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *MiningProfitDetailFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[2].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *MiningProfitDetailFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(miningprofitdetail.FieldID))
}

// WhereCreatedAt applies the entql uint32 predicate on the created_at field.
func (f *MiningProfitDetailFilter) WhereCreatedAt(p entql.Uint32P) {
	f.Where(p.Field(miningprofitdetail.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql uint32 predicate on the updated_at field.
func (f *MiningProfitDetailFilter) WhereUpdatedAt(p entql.Uint32P) {
	f.Where(p.Field(miningprofitdetail.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql uint32 predicate on the deleted_at field.
func (f *MiningProfitDetailFilter) WhereDeletedAt(p entql.Uint32P) {
	f.Where(p.Field(miningprofitdetail.FieldDeletedAt))
}

// WhereGoodID applies the entql [16]byte predicate on the good_id field.
func (f *MiningProfitDetailFilter) WhereGoodID(p entql.ValueP) {
	f.Where(p.Field(miningprofitdetail.FieldGoodID))
}

// WhereCoinTypeID applies the entql [16]byte predicate on the coin_type_id field.
func (f *MiningProfitDetailFilter) WhereCoinTypeID(p entql.ValueP) {
	f.Where(p.Field(miningprofitdetail.FieldCoinTypeID))
}

// WhereAmount applies the entql float64 predicate on the amount field.
func (f *MiningProfitDetailFilter) WhereAmount(p entql.Float64P) {
	f.Where(p.Field(miningprofitdetail.FieldAmount))
}

// WhereBenefitDate applies the entql uint32 predicate on the benefit_date field.
func (f *MiningProfitDetailFilter) WhereBenefitDate(p entql.Uint32P) {
	f.Where(p.Field(miningprofitdetail.FieldBenefitDate))
}

// addPredicate implements the predicateAdder interface.
func (mpgq *MiningProfitGeneralQuery) addPredicate(pred func(s *sql.Selector)) {
	mpgq.predicates = append(mpgq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the MiningProfitGeneralQuery builder.
func (mpgq *MiningProfitGeneralQuery) Filter() *MiningProfitGeneralFilter {
	return &MiningProfitGeneralFilter{config: mpgq.config, predicateAdder: mpgq}
}

// addPredicate implements the predicateAdder interface.
func (m *MiningProfitGeneralMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the MiningProfitGeneralMutation builder.
func (m *MiningProfitGeneralMutation) Filter() *MiningProfitGeneralFilter {
	return &MiningProfitGeneralFilter{config: m.config, predicateAdder: m}
}

// MiningProfitGeneralFilter provides a generic filtering capability at runtime for MiningProfitGeneralQuery.
type MiningProfitGeneralFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *MiningProfitGeneralFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[3].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *MiningProfitGeneralFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(miningprofitgeneral.FieldID))
}

// WhereCreatedAt applies the entql uint32 predicate on the created_at field.
func (f *MiningProfitGeneralFilter) WhereCreatedAt(p entql.Uint32P) {
	f.Where(p.Field(miningprofitgeneral.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql uint32 predicate on the updated_at field.
func (f *MiningProfitGeneralFilter) WhereUpdatedAt(p entql.Uint32P) {
	f.Where(p.Field(miningprofitgeneral.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql uint32 predicate on the deleted_at field.
func (f *MiningProfitGeneralFilter) WhereDeletedAt(p entql.Uint32P) {
	f.Where(p.Field(miningprofitgeneral.FieldDeletedAt))
}

// WhereGoodID applies the entql [16]byte predicate on the good_id field.
func (f *MiningProfitGeneralFilter) WhereGoodID(p entql.ValueP) {
	f.Where(p.Field(miningprofitgeneral.FieldGoodID))
}

// WhereCoinTypeID applies the entql [16]byte predicate on the coin_type_id field.
func (f *MiningProfitGeneralFilter) WhereCoinTypeID(p entql.ValueP) {
	f.Where(p.Field(miningprofitgeneral.FieldCoinTypeID))
}

// WhereAmount applies the entql float64 predicate on the amount field.
func (f *MiningProfitGeneralFilter) WhereAmount(p entql.Float64P) {
	f.Where(p.Field(miningprofitgeneral.FieldAmount))
}

// WhereToPlatform applies the entql float64 predicate on the to_platform field.
func (f *MiningProfitGeneralFilter) WhereToPlatform(p entql.Float64P) {
	f.Where(p.Field(miningprofitgeneral.FieldToPlatform))
}

// WhereToUser applies the entql float64 predicate on the to_user field.
func (f *MiningProfitGeneralFilter) WhereToUser(p entql.Float64P) {
	f.Where(p.Field(miningprofitgeneral.FieldToUser))
}

// addPredicate implements the predicateAdder interface.
func (mpuq *MiningProfitUnsoldQuery) addPredicate(pred func(s *sql.Selector)) {
	mpuq.predicates = append(mpuq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the MiningProfitUnsoldQuery builder.
func (mpuq *MiningProfitUnsoldQuery) Filter() *MiningProfitUnsoldFilter {
	return &MiningProfitUnsoldFilter{config: mpuq.config, predicateAdder: mpuq}
}

// addPredicate implements the predicateAdder interface.
func (m *MiningProfitUnsoldMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the MiningProfitUnsoldMutation builder.
func (m *MiningProfitUnsoldMutation) Filter() *MiningProfitUnsoldFilter {
	return &MiningProfitUnsoldFilter{config: m.config, predicateAdder: m}
}

// MiningProfitUnsoldFilter provides a generic filtering capability at runtime for MiningProfitUnsoldQuery.
type MiningProfitUnsoldFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *MiningProfitUnsoldFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[4].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *MiningProfitUnsoldFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(miningprofitunsold.FieldID))
}

// WhereCreatedAt applies the entql uint32 predicate on the created_at field.
func (f *MiningProfitUnsoldFilter) WhereCreatedAt(p entql.Uint32P) {
	f.Where(p.Field(miningprofitunsold.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql uint32 predicate on the updated_at field.
func (f *MiningProfitUnsoldFilter) WhereUpdatedAt(p entql.Uint32P) {
	f.Where(p.Field(miningprofitunsold.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql uint32 predicate on the deleted_at field.
func (f *MiningProfitUnsoldFilter) WhereDeletedAt(p entql.Uint32P) {
	f.Where(p.Field(miningprofitunsold.FieldDeletedAt))
}

// WhereGoodID applies the entql [16]byte predicate on the good_id field.
func (f *MiningProfitUnsoldFilter) WhereGoodID(p entql.ValueP) {
	f.Where(p.Field(miningprofitunsold.FieldGoodID))
}

// WhereCoinTypeID applies the entql [16]byte predicate on the coin_type_id field.
func (f *MiningProfitUnsoldFilter) WhereCoinTypeID(p entql.ValueP) {
	f.Where(p.Field(miningprofitunsold.FieldCoinTypeID))
}

// WhereAmount applies the entql float64 predicate on the amount field.
func (f *MiningProfitUnsoldFilter) WhereAmount(p entql.Float64P) {
	f.Where(p.Field(miningprofitunsold.FieldAmount))
}

// WhereBenefitDate applies the entql uint32 predicate on the benefit_date field.
func (f *MiningProfitUnsoldFilter) WhereBenefitDate(p entql.Uint32P) {
	f.Where(p.Field(miningprofitunsold.FieldBenefitDate))
}

// addPredicate implements the predicateAdder interface.
func (pq *ProfitQuery) addPredicate(pred func(s *sql.Selector)) {
	pq.predicates = append(pq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the ProfitQuery builder.
func (pq *ProfitQuery) Filter() *ProfitFilter {
	return &ProfitFilter{config: pq.config, predicateAdder: pq}
}

// addPredicate implements the predicateAdder interface.
func (m *ProfitMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the ProfitMutation builder.
func (m *ProfitMutation) Filter() *ProfitFilter {
	return &ProfitFilter{config: m.config, predicateAdder: m}
}

// ProfitFilter provides a generic filtering capability at runtime for ProfitQuery.
type ProfitFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *ProfitFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[5].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *ProfitFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(profit.FieldID))
}

// WhereCreatedAt applies the entql uint32 predicate on the created_at field.
func (f *ProfitFilter) WhereCreatedAt(p entql.Uint32P) {
	f.Where(p.Field(profit.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql uint32 predicate on the updated_at field.
func (f *ProfitFilter) WhereUpdatedAt(p entql.Uint32P) {
	f.Where(p.Field(profit.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql uint32 predicate on the deleted_at field.
func (f *ProfitFilter) WhereDeletedAt(p entql.Uint32P) {
	f.Where(p.Field(profit.FieldDeletedAt))
}

// WhereAppID applies the entql [16]byte predicate on the app_id field.
func (f *ProfitFilter) WhereAppID(p entql.ValueP) {
	f.Where(p.Field(profit.FieldAppID))
}

// WhereUserID applies the entql [16]byte predicate on the user_id field.
func (f *ProfitFilter) WhereUserID(p entql.ValueP) {
	f.Where(p.Field(profit.FieldUserID))
}

// WhereCoinTypeID applies the entql [16]byte predicate on the coin_type_id field.
func (f *ProfitFilter) WhereCoinTypeID(p entql.ValueP) {
	f.Where(p.Field(profit.FieldCoinTypeID))
}

// WhereIncoming applies the entql float64 predicate on the incoming field.
func (f *ProfitFilter) WhereIncoming(p entql.Float64P) {
	f.Where(p.Field(profit.FieldIncoming))
}

// addPredicate implements the predicateAdder interface.
func (wq *WithdrawQuery) addPredicate(pred func(s *sql.Selector)) {
	wq.predicates = append(wq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the WithdrawQuery builder.
func (wq *WithdrawQuery) Filter() *WithdrawFilter {
	return &WithdrawFilter{config: wq.config, predicateAdder: wq}
}

// addPredicate implements the predicateAdder interface.
func (m *WithdrawMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the WithdrawMutation builder.
func (m *WithdrawMutation) Filter() *WithdrawFilter {
	return &WithdrawFilter{config: m.config, predicateAdder: m}
}

// WithdrawFilter provides a generic filtering capability at runtime for WithdrawQuery.
type WithdrawFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *WithdrawFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[6].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *WithdrawFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(withdraw.FieldID))
}

// WhereCreatedAt applies the entql uint32 predicate on the created_at field.
func (f *WithdrawFilter) WhereCreatedAt(p entql.Uint32P) {
	f.Where(p.Field(withdraw.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql uint32 predicate on the updated_at field.
func (f *WithdrawFilter) WhereUpdatedAt(p entql.Uint32P) {
	f.Where(p.Field(withdraw.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql uint32 predicate on the deleted_at field.
func (f *WithdrawFilter) WhereDeletedAt(p entql.Uint32P) {
	f.Where(p.Field(withdraw.FieldDeletedAt))
}

// WhereAppID applies the entql [16]byte predicate on the app_id field.
func (f *WithdrawFilter) WhereAppID(p entql.ValueP) {
	f.Where(p.Field(withdraw.FieldAppID))
}

// WhereUserID applies the entql [16]byte predicate on the user_id field.
func (f *WithdrawFilter) WhereUserID(p entql.ValueP) {
	f.Where(p.Field(withdraw.FieldUserID))
}

// WhereCoinTypeID applies the entql [16]byte predicate on the coin_type_id field.
func (f *WithdrawFilter) WhereCoinTypeID(p entql.ValueP) {
	f.Where(p.Field(withdraw.FieldCoinTypeID))
}

// WhereAccountID applies the entql [16]byte predicate on the account_id field.
func (f *WithdrawFilter) WhereAccountID(p entql.ValueP) {
	f.Where(p.Field(withdraw.FieldAccountID))
}

// WherePlatformTransactionID applies the entql [16]byte predicate on the platform_transaction_id field.
func (f *WithdrawFilter) WherePlatformTransactionID(p entql.ValueP) {
	f.Where(p.Field(withdraw.FieldPlatformTransactionID))
}

// WhereChainTransactionID applies the entql string predicate on the chain_transaction_id field.
func (f *WithdrawFilter) WhereChainTransactionID(p entql.StringP) {
	f.Where(p.Field(withdraw.FieldChainTransactionID))
}

// WhereState applies the entql string predicate on the state field.
func (f *WithdrawFilter) WhereState(p entql.StringP) {
	f.Where(p.Field(withdraw.FieldState))
}

// WhereAmount applies the entql float64 predicate on the amount field.
func (f *WithdrawFilter) WhereAmount(p entql.Float64P) {
	f.Where(p.Field(withdraw.FieldAmount))
}
