// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/ledger-manager/pkg/db/ent/miningprofitunsold"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// MiningProfitUnsold is the model entity for the MiningProfitUnsold schema.
type MiningProfitUnsold struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt uint32 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt uint32 `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt uint32 `json:"deleted_at,omitempty"`
	// GoodID holds the value of the "good_id" field.
	GoodID uuid.UUID `json:"good_id,omitempty"`
	// CoinTypeID holds the value of the "coin_type_id" field.
	CoinTypeID uuid.UUID `json:"coin_type_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount decimal.Decimal `json:"amount,omitempty"`
	// BenefitDate holds the value of the "benefit_date" field.
	BenefitDate uint32 `json:"benefit_date,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MiningProfitUnsold) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case miningprofitunsold.FieldAmount:
			values[i] = new(decimal.Decimal)
		case miningprofitunsold.FieldCreatedAt, miningprofitunsold.FieldUpdatedAt, miningprofitunsold.FieldDeletedAt, miningprofitunsold.FieldBenefitDate:
			values[i] = new(sql.NullInt64)
		case miningprofitunsold.FieldID, miningprofitunsold.FieldGoodID, miningprofitunsold.FieldCoinTypeID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type MiningProfitUnsold", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MiningProfitUnsold fields.
func (mpu *MiningProfitUnsold) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case miningprofitunsold.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				mpu.ID = *value
			}
		case miningprofitunsold.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				mpu.CreatedAt = uint32(value.Int64)
			}
		case miningprofitunsold.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				mpu.UpdatedAt = uint32(value.Int64)
			}
		case miningprofitunsold.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				mpu.DeletedAt = uint32(value.Int64)
			}
		case miningprofitunsold.FieldGoodID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field good_id", values[i])
			} else if value != nil {
				mpu.GoodID = *value
			}
		case miningprofitunsold.FieldCoinTypeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field coin_type_id", values[i])
			} else if value != nil {
				mpu.CoinTypeID = *value
			}
		case miningprofitunsold.FieldAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value != nil {
				mpu.Amount = *value
			}
		case miningprofitunsold.FieldBenefitDate:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field benefit_date", values[i])
			} else if value.Valid {
				mpu.BenefitDate = uint32(value.Int64)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this MiningProfitUnsold.
// Note that you need to call MiningProfitUnsold.Unwrap() before calling this method if this MiningProfitUnsold
// was returned from a transaction, and the transaction was committed or rolled back.
func (mpu *MiningProfitUnsold) Update() *MiningProfitUnsoldUpdateOne {
	return (&MiningProfitUnsoldClient{config: mpu.config}).UpdateOne(mpu)
}

// Unwrap unwraps the MiningProfitUnsold entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mpu *MiningProfitUnsold) Unwrap() *MiningProfitUnsold {
	_tx, ok := mpu.config.driver.(*txDriver)
	if !ok {
		panic("ent: MiningProfitUnsold is not a transactional entity")
	}
	mpu.config.driver = _tx.drv
	return mpu
}

// String implements the fmt.Stringer.
func (mpu *MiningProfitUnsold) String() string {
	var builder strings.Builder
	builder.WriteString("MiningProfitUnsold(")
	builder.WriteString(fmt.Sprintf("id=%v, ", mpu.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", mpu.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", mpu.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", mpu.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("good_id=")
	builder.WriteString(fmt.Sprintf("%v", mpu.GoodID))
	builder.WriteString(", ")
	builder.WriteString("coin_type_id=")
	builder.WriteString(fmt.Sprintf("%v", mpu.CoinTypeID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", mpu.Amount))
	builder.WriteString(", ")
	builder.WriteString("benefit_date=")
	builder.WriteString(fmt.Sprintf("%v", mpu.BenefitDate))
	builder.WriteByte(')')
	return builder.String()
}

// MiningProfitUnsolds is a parsable slice of MiningProfitUnsold.
type MiningProfitUnsolds []*MiningProfitUnsold

func (mpu MiningProfitUnsolds) config(cfg config) {
	for _i := range mpu {
		mpu[_i].config = cfg
	}
}
