// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/ledger-manager/pkg/db/ent/miningprofitunsold"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// MiningProfitUnsoldCreate is the builder for creating a MiningProfitUnsold entity.
type MiningProfitUnsoldCreate struct {
	config
	mutation *MiningProfitUnsoldMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (mpuc *MiningProfitUnsoldCreate) SetCreatedAt(u uint32) *MiningProfitUnsoldCreate {
	mpuc.mutation.SetCreatedAt(u)
	return mpuc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mpuc *MiningProfitUnsoldCreate) SetNillableCreatedAt(u *uint32) *MiningProfitUnsoldCreate {
	if u != nil {
		mpuc.SetCreatedAt(*u)
	}
	return mpuc
}

// SetUpdatedAt sets the "updated_at" field.
func (mpuc *MiningProfitUnsoldCreate) SetUpdatedAt(u uint32) *MiningProfitUnsoldCreate {
	mpuc.mutation.SetUpdatedAt(u)
	return mpuc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (mpuc *MiningProfitUnsoldCreate) SetNillableUpdatedAt(u *uint32) *MiningProfitUnsoldCreate {
	if u != nil {
		mpuc.SetUpdatedAt(*u)
	}
	return mpuc
}

// SetDeletedAt sets the "deleted_at" field.
func (mpuc *MiningProfitUnsoldCreate) SetDeletedAt(u uint32) *MiningProfitUnsoldCreate {
	mpuc.mutation.SetDeletedAt(u)
	return mpuc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (mpuc *MiningProfitUnsoldCreate) SetNillableDeletedAt(u *uint32) *MiningProfitUnsoldCreate {
	if u != nil {
		mpuc.SetDeletedAt(*u)
	}
	return mpuc
}

// SetGoodID sets the "good_id" field.
func (mpuc *MiningProfitUnsoldCreate) SetGoodID(u uuid.UUID) *MiningProfitUnsoldCreate {
	mpuc.mutation.SetGoodID(u)
	return mpuc
}

// SetNillableGoodID sets the "good_id" field if the given value is not nil.
func (mpuc *MiningProfitUnsoldCreate) SetNillableGoodID(u *uuid.UUID) *MiningProfitUnsoldCreate {
	if u != nil {
		mpuc.SetGoodID(*u)
	}
	return mpuc
}

// SetCoinTypeID sets the "coin_type_id" field.
func (mpuc *MiningProfitUnsoldCreate) SetCoinTypeID(u uuid.UUID) *MiningProfitUnsoldCreate {
	mpuc.mutation.SetCoinTypeID(u)
	return mpuc
}

// SetNillableCoinTypeID sets the "coin_type_id" field if the given value is not nil.
func (mpuc *MiningProfitUnsoldCreate) SetNillableCoinTypeID(u *uuid.UUID) *MiningProfitUnsoldCreate {
	if u != nil {
		mpuc.SetCoinTypeID(*u)
	}
	return mpuc
}

// SetAmount sets the "amount" field.
func (mpuc *MiningProfitUnsoldCreate) SetAmount(d decimal.Decimal) *MiningProfitUnsoldCreate {
	mpuc.mutation.SetAmount(d)
	return mpuc
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (mpuc *MiningProfitUnsoldCreate) SetNillableAmount(d *decimal.Decimal) *MiningProfitUnsoldCreate {
	if d != nil {
		mpuc.SetAmount(*d)
	}
	return mpuc
}

// SetBenefitDate sets the "benefit_date" field.
func (mpuc *MiningProfitUnsoldCreate) SetBenefitDate(u uint32) *MiningProfitUnsoldCreate {
	mpuc.mutation.SetBenefitDate(u)
	return mpuc
}

// SetNillableBenefitDate sets the "benefit_date" field if the given value is not nil.
func (mpuc *MiningProfitUnsoldCreate) SetNillableBenefitDate(u *uint32) *MiningProfitUnsoldCreate {
	if u != nil {
		mpuc.SetBenefitDate(*u)
	}
	return mpuc
}

// SetID sets the "id" field.
func (mpuc *MiningProfitUnsoldCreate) SetID(u uuid.UUID) *MiningProfitUnsoldCreate {
	mpuc.mutation.SetID(u)
	return mpuc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (mpuc *MiningProfitUnsoldCreate) SetNillableID(u *uuid.UUID) *MiningProfitUnsoldCreate {
	if u != nil {
		mpuc.SetID(*u)
	}
	return mpuc
}

// Mutation returns the MiningProfitUnsoldMutation object of the builder.
func (mpuc *MiningProfitUnsoldCreate) Mutation() *MiningProfitUnsoldMutation {
	return mpuc.mutation
}

// Save creates the MiningProfitUnsold in the database.
func (mpuc *MiningProfitUnsoldCreate) Save(ctx context.Context) (*MiningProfitUnsold, error) {
	var (
		err  error
		node *MiningProfitUnsold
	)
	if err := mpuc.defaults(); err != nil {
		return nil, err
	}
	if len(mpuc.hooks) == 0 {
		if err = mpuc.check(); err != nil {
			return nil, err
		}
		node, err = mpuc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MiningProfitUnsoldMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mpuc.check(); err != nil {
				return nil, err
			}
			mpuc.mutation = mutation
			if node, err = mpuc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(mpuc.hooks) - 1; i >= 0; i-- {
			if mpuc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mpuc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, mpuc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*MiningProfitUnsold)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from MiningProfitUnsoldMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mpuc *MiningProfitUnsoldCreate) SaveX(ctx context.Context) *MiningProfitUnsold {
	v, err := mpuc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mpuc *MiningProfitUnsoldCreate) Exec(ctx context.Context) error {
	_, err := mpuc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpuc *MiningProfitUnsoldCreate) ExecX(ctx context.Context) {
	if err := mpuc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mpuc *MiningProfitUnsoldCreate) defaults() error {
	if _, ok := mpuc.mutation.CreatedAt(); !ok {
		if miningprofitunsold.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized miningprofitunsold.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := miningprofitunsold.DefaultCreatedAt()
		mpuc.mutation.SetCreatedAt(v)
	}
	if _, ok := mpuc.mutation.UpdatedAt(); !ok {
		if miningprofitunsold.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized miningprofitunsold.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := miningprofitunsold.DefaultUpdatedAt()
		mpuc.mutation.SetUpdatedAt(v)
	}
	if _, ok := mpuc.mutation.DeletedAt(); !ok {
		if miningprofitunsold.DefaultDeletedAt == nil {
			return fmt.Errorf("ent: uninitialized miningprofitunsold.DefaultDeletedAt (forgotten import ent/runtime?)")
		}
		v := miningprofitunsold.DefaultDeletedAt()
		mpuc.mutation.SetDeletedAt(v)
	}
	if _, ok := mpuc.mutation.GoodID(); !ok {
		if miningprofitunsold.DefaultGoodID == nil {
			return fmt.Errorf("ent: uninitialized miningprofitunsold.DefaultGoodID (forgotten import ent/runtime?)")
		}
		v := miningprofitunsold.DefaultGoodID()
		mpuc.mutation.SetGoodID(v)
	}
	if _, ok := mpuc.mutation.CoinTypeID(); !ok {
		if miningprofitunsold.DefaultCoinTypeID == nil {
			return fmt.Errorf("ent: uninitialized miningprofitunsold.DefaultCoinTypeID (forgotten import ent/runtime?)")
		}
		v := miningprofitunsold.DefaultCoinTypeID()
		mpuc.mutation.SetCoinTypeID(v)
	}
	if _, ok := mpuc.mutation.BenefitDate(); !ok {
		v := miningprofitunsold.DefaultBenefitDate
		mpuc.mutation.SetBenefitDate(v)
	}
	if _, ok := mpuc.mutation.ID(); !ok {
		if miningprofitunsold.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized miningprofitunsold.DefaultID (forgotten import ent/runtime?)")
		}
		v := miningprofitunsold.DefaultID()
		mpuc.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (mpuc *MiningProfitUnsoldCreate) check() error {
	if _, ok := mpuc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MiningProfitUnsold.created_at"`)}
	}
	if _, ok := mpuc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MiningProfitUnsold.updated_at"`)}
	}
	if _, ok := mpuc.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "MiningProfitUnsold.deleted_at"`)}
	}
	return nil
}

func (mpuc *MiningProfitUnsoldCreate) sqlSave(ctx context.Context) (*MiningProfitUnsold, error) {
	_node, _spec := mpuc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mpuc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (mpuc *MiningProfitUnsoldCreate) createSpec() (*MiningProfitUnsold, *sqlgraph.CreateSpec) {
	var (
		_node = &MiningProfitUnsold{config: mpuc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: miningprofitunsold.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: miningprofitunsold.FieldID,
			},
		}
	)
	_spec.OnConflict = mpuc.conflict
	if id, ok := mpuc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := mpuc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: miningprofitunsold.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := mpuc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: miningprofitunsold.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := mpuc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: miningprofitunsold.FieldDeletedAt,
		})
		_node.DeletedAt = value
	}
	if value, ok := mpuc.mutation.GoodID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: miningprofitunsold.FieldGoodID,
		})
		_node.GoodID = value
	}
	if value, ok := mpuc.mutation.CoinTypeID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: miningprofitunsold.FieldCoinTypeID,
		})
		_node.CoinTypeID = value
	}
	if value, ok := mpuc.mutation.Amount(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: miningprofitunsold.FieldAmount,
		})
		_node.Amount = value
	}
	if value, ok := mpuc.mutation.BenefitDate(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: miningprofitunsold.FieldBenefitDate,
		})
		_node.BenefitDate = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MiningProfitUnsold.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MiningProfitUnsoldUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (mpuc *MiningProfitUnsoldCreate) OnConflict(opts ...sql.ConflictOption) *MiningProfitUnsoldUpsertOne {
	mpuc.conflict = opts
	return &MiningProfitUnsoldUpsertOne{
		create: mpuc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MiningProfitUnsold.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (mpuc *MiningProfitUnsoldCreate) OnConflictColumns(columns ...string) *MiningProfitUnsoldUpsertOne {
	mpuc.conflict = append(mpuc.conflict, sql.ConflictColumns(columns...))
	return &MiningProfitUnsoldUpsertOne{
		create: mpuc,
	}
}

type (
	// MiningProfitUnsoldUpsertOne is the builder for "upsert"-ing
	//  one MiningProfitUnsold node.
	MiningProfitUnsoldUpsertOne struct {
		create *MiningProfitUnsoldCreate
	}

	// MiningProfitUnsoldUpsert is the "OnConflict" setter.
	MiningProfitUnsoldUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *MiningProfitUnsoldUpsert) SetCreatedAt(v uint32) *MiningProfitUnsoldUpsert {
	u.Set(miningprofitunsold.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsert) UpdateCreatedAt() *MiningProfitUnsoldUpsert {
	u.SetExcluded(miningprofitunsold.FieldCreatedAt)
	return u
}

// AddCreatedAt adds v to the "created_at" field.
func (u *MiningProfitUnsoldUpsert) AddCreatedAt(v uint32) *MiningProfitUnsoldUpsert {
	u.Add(miningprofitunsold.FieldCreatedAt, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MiningProfitUnsoldUpsert) SetUpdatedAt(v uint32) *MiningProfitUnsoldUpsert {
	u.Set(miningprofitunsold.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsert) UpdateUpdatedAt() *MiningProfitUnsoldUpsert {
	u.SetExcluded(miningprofitunsold.FieldUpdatedAt)
	return u
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *MiningProfitUnsoldUpsert) AddUpdatedAt(v uint32) *MiningProfitUnsoldUpsert {
	u.Add(miningprofitunsold.FieldUpdatedAt, v)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *MiningProfitUnsoldUpsert) SetDeletedAt(v uint32) *MiningProfitUnsoldUpsert {
	u.Set(miningprofitunsold.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsert) UpdateDeletedAt() *MiningProfitUnsoldUpsert {
	u.SetExcluded(miningprofitunsold.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *MiningProfitUnsoldUpsert) AddDeletedAt(v uint32) *MiningProfitUnsoldUpsert {
	u.Add(miningprofitunsold.FieldDeletedAt, v)
	return u
}

// SetGoodID sets the "good_id" field.
func (u *MiningProfitUnsoldUpsert) SetGoodID(v uuid.UUID) *MiningProfitUnsoldUpsert {
	u.Set(miningprofitunsold.FieldGoodID, v)
	return u
}

// UpdateGoodID sets the "good_id" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsert) UpdateGoodID() *MiningProfitUnsoldUpsert {
	u.SetExcluded(miningprofitunsold.FieldGoodID)
	return u
}

// ClearGoodID clears the value of the "good_id" field.
func (u *MiningProfitUnsoldUpsert) ClearGoodID() *MiningProfitUnsoldUpsert {
	u.SetNull(miningprofitunsold.FieldGoodID)
	return u
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *MiningProfitUnsoldUpsert) SetCoinTypeID(v uuid.UUID) *MiningProfitUnsoldUpsert {
	u.Set(miningprofitunsold.FieldCoinTypeID, v)
	return u
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsert) UpdateCoinTypeID() *MiningProfitUnsoldUpsert {
	u.SetExcluded(miningprofitunsold.FieldCoinTypeID)
	return u
}

// ClearCoinTypeID clears the value of the "coin_type_id" field.
func (u *MiningProfitUnsoldUpsert) ClearCoinTypeID() *MiningProfitUnsoldUpsert {
	u.SetNull(miningprofitunsold.FieldCoinTypeID)
	return u
}

// SetAmount sets the "amount" field.
func (u *MiningProfitUnsoldUpsert) SetAmount(v decimal.Decimal) *MiningProfitUnsoldUpsert {
	u.Set(miningprofitunsold.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsert) UpdateAmount() *MiningProfitUnsoldUpsert {
	u.SetExcluded(miningprofitunsold.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *MiningProfitUnsoldUpsert) AddAmount(v decimal.Decimal) *MiningProfitUnsoldUpsert {
	u.Add(miningprofitunsold.FieldAmount, v)
	return u
}

// ClearAmount clears the value of the "amount" field.
func (u *MiningProfitUnsoldUpsert) ClearAmount() *MiningProfitUnsoldUpsert {
	u.SetNull(miningprofitunsold.FieldAmount)
	return u
}

// SetBenefitDate sets the "benefit_date" field.
func (u *MiningProfitUnsoldUpsert) SetBenefitDate(v uint32) *MiningProfitUnsoldUpsert {
	u.Set(miningprofitunsold.FieldBenefitDate, v)
	return u
}

// UpdateBenefitDate sets the "benefit_date" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsert) UpdateBenefitDate() *MiningProfitUnsoldUpsert {
	u.SetExcluded(miningprofitunsold.FieldBenefitDate)
	return u
}

// AddBenefitDate adds v to the "benefit_date" field.
func (u *MiningProfitUnsoldUpsert) AddBenefitDate(v uint32) *MiningProfitUnsoldUpsert {
	u.Add(miningprofitunsold.FieldBenefitDate, v)
	return u
}

// ClearBenefitDate clears the value of the "benefit_date" field.
func (u *MiningProfitUnsoldUpsert) ClearBenefitDate() *MiningProfitUnsoldUpsert {
	u.SetNull(miningprofitunsold.FieldBenefitDate)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.MiningProfitUnsold.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(miningprofitunsold.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *MiningProfitUnsoldUpsertOne) UpdateNewValues() *MiningProfitUnsoldUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(miningprofitunsold.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.MiningProfitUnsold.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *MiningProfitUnsoldUpsertOne) Ignore() *MiningProfitUnsoldUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MiningProfitUnsoldUpsertOne) DoNothing() *MiningProfitUnsoldUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MiningProfitUnsoldCreate.OnConflict
// documentation for more info.
func (u *MiningProfitUnsoldUpsertOne) Update(set func(*MiningProfitUnsoldUpsert)) *MiningProfitUnsoldUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MiningProfitUnsoldUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *MiningProfitUnsoldUpsertOne) SetCreatedAt(v uint32) *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *MiningProfitUnsoldUpsertOne) AddCreatedAt(v uint32) *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsertOne) UpdateCreatedAt() *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MiningProfitUnsoldUpsertOne) SetUpdatedAt(v uint32) *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *MiningProfitUnsoldUpsertOne) AddUpdatedAt(v uint32) *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsertOne) UpdateUpdatedAt() *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *MiningProfitUnsoldUpsertOne) SetDeletedAt(v uint32) *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *MiningProfitUnsoldUpsertOne) AddDeletedAt(v uint32) *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsertOne) UpdateDeletedAt() *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetGoodID sets the "good_id" field.
func (u *MiningProfitUnsoldUpsertOne) SetGoodID(v uuid.UUID) *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.SetGoodID(v)
	})
}

// UpdateGoodID sets the "good_id" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsertOne) UpdateGoodID() *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.UpdateGoodID()
	})
}

// ClearGoodID clears the value of the "good_id" field.
func (u *MiningProfitUnsoldUpsertOne) ClearGoodID() *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.ClearGoodID()
	})
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *MiningProfitUnsoldUpsertOne) SetCoinTypeID(v uuid.UUID) *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.SetCoinTypeID(v)
	})
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsertOne) UpdateCoinTypeID() *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.UpdateCoinTypeID()
	})
}

// ClearCoinTypeID clears the value of the "coin_type_id" field.
func (u *MiningProfitUnsoldUpsertOne) ClearCoinTypeID() *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.ClearCoinTypeID()
	})
}

// SetAmount sets the "amount" field.
func (u *MiningProfitUnsoldUpsertOne) SetAmount(v decimal.Decimal) *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *MiningProfitUnsoldUpsertOne) AddAmount(v decimal.Decimal) *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsertOne) UpdateAmount() *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.UpdateAmount()
	})
}

// ClearAmount clears the value of the "amount" field.
func (u *MiningProfitUnsoldUpsertOne) ClearAmount() *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.ClearAmount()
	})
}

// SetBenefitDate sets the "benefit_date" field.
func (u *MiningProfitUnsoldUpsertOne) SetBenefitDate(v uint32) *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.SetBenefitDate(v)
	})
}

// AddBenefitDate adds v to the "benefit_date" field.
func (u *MiningProfitUnsoldUpsertOne) AddBenefitDate(v uint32) *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.AddBenefitDate(v)
	})
}

// UpdateBenefitDate sets the "benefit_date" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsertOne) UpdateBenefitDate() *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.UpdateBenefitDate()
	})
}

// ClearBenefitDate clears the value of the "benefit_date" field.
func (u *MiningProfitUnsoldUpsertOne) ClearBenefitDate() *MiningProfitUnsoldUpsertOne {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.ClearBenefitDate()
	})
}

// Exec executes the query.
func (u *MiningProfitUnsoldUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MiningProfitUnsoldCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MiningProfitUnsoldUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MiningProfitUnsoldUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: MiningProfitUnsoldUpsertOne.ID is not supported by MySQL driver. Use MiningProfitUnsoldUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MiningProfitUnsoldUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MiningProfitUnsoldCreateBulk is the builder for creating many MiningProfitUnsold entities in bulk.
type MiningProfitUnsoldCreateBulk struct {
	config
	builders []*MiningProfitUnsoldCreate
	conflict []sql.ConflictOption
}

// Save creates the MiningProfitUnsold entities in the database.
func (mpucb *MiningProfitUnsoldCreateBulk) Save(ctx context.Context) ([]*MiningProfitUnsold, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mpucb.builders))
	nodes := make([]*MiningProfitUnsold, len(mpucb.builders))
	mutators := make([]Mutator, len(mpucb.builders))
	for i := range mpucb.builders {
		func(i int, root context.Context) {
			builder := mpucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MiningProfitUnsoldMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mpucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = mpucb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mpucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mpucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mpucb *MiningProfitUnsoldCreateBulk) SaveX(ctx context.Context) []*MiningProfitUnsold {
	v, err := mpucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mpucb *MiningProfitUnsoldCreateBulk) Exec(ctx context.Context) error {
	_, err := mpucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpucb *MiningProfitUnsoldCreateBulk) ExecX(ctx context.Context) {
	if err := mpucb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MiningProfitUnsold.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MiningProfitUnsoldUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (mpucb *MiningProfitUnsoldCreateBulk) OnConflict(opts ...sql.ConflictOption) *MiningProfitUnsoldUpsertBulk {
	mpucb.conflict = opts
	return &MiningProfitUnsoldUpsertBulk{
		create: mpucb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MiningProfitUnsold.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (mpucb *MiningProfitUnsoldCreateBulk) OnConflictColumns(columns ...string) *MiningProfitUnsoldUpsertBulk {
	mpucb.conflict = append(mpucb.conflict, sql.ConflictColumns(columns...))
	return &MiningProfitUnsoldUpsertBulk{
		create: mpucb,
	}
}

// MiningProfitUnsoldUpsertBulk is the builder for "upsert"-ing
// a bulk of MiningProfitUnsold nodes.
type MiningProfitUnsoldUpsertBulk struct {
	create *MiningProfitUnsoldCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MiningProfitUnsold.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(miningprofitunsold.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *MiningProfitUnsoldUpsertBulk) UpdateNewValues() *MiningProfitUnsoldUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(miningprofitunsold.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MiningProfitUnsold.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *MiningProfitUnsoldUpsertBulk) Ignore() *MiningProfitUnsoldUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MiningProfitUnsoldUpsertBulk) DoNothing() *MiningProfitUnsoldUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MiningProfitUnsoldCreateBulk.OnConflict
// documentation for more info.
func (u *MiningProfitUnsoldUpsertBulk) Update(set func(*MiningProfitUnsoldUpsert)) *MiningProfitUnsoldUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MiningProfitUnsoldUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *MiningProfitUnsoldUpsertBulk) SetCreatedAt(v uint32) *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *MiningProfitUnsoldUpsertBulk) AddCreatedAt(v uint32) *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsertBulk) UpdateCreatedAt() *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MiningProfitUnsoldUpsertBulk) SetUpdatedAt(v uint32) *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *MiningProfitUnsoldUpsertBulk) AddUpdatedAt(v uint32) *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsertBulk) UpdateUpdatedAt() *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *MiningProfitUnsoldUpsertBulk) SetDeletedAt(v uint32) *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *MiningProfitUnsoldUpsertBulk) AddDeletedAt(v uint32) *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsertBulk) UpdateDeletedAt() *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetGoodID sets the "good_id" field.
func (u *MiningProfitUnsoldUpsertBulk) SetGoodID(v uuid.UUID) *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.SetGoodID(v)
	})
}

// UpdateGoodID sets the "good_id" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsertBulk) UpdateGoodID() *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.UpdateGoodID()
	})
}

// ClearGoodID clears the value of the "good_id" field.
func (u *MiningProfitUnsoldUpsertBulk) ClearGoodID() *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.ClearGoodID()
	})
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *MiningProfitUnsoldUpsertBulk) SetCoinTypeID(v uuid.UUID) *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.SetCoinTypeID(v)
	})
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsertBulk) UpdateCoinTypeID() *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.UpdateCoinTypeID()
	})
}

// ClearCoinTypeID clears the value of the "coin_type_id" field.
func (u *MiningProfitUnsoldUpsertBulk) ClearCoinTypeID() *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.ClearCoinTypeID()
	})
}

// SetAmount sets the "amount" field.
func (u *MiningProfitUnsoldUpsertBulk) SetAmount(v decimal.Decimal) *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *MiningProfitUnsoldUpsertBulk) AddAmount(v decimal.Decimal) *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsertBulk) UpdateAmount() *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.UpdateAmount()
	})
}

// ClearAmount clears the value of the "amount" field.
func (u *MiningProfitUnsoldUpsertBulk) ClearAmount() *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.ClearAmount()
	})
}

// SetBenefitDate sets the "benefit_date" field.
func (u *MiningProfitUnsoldUpsertBulk) SetBenefitDate(v uint32) *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.SetBenefitDate(v)
	})
}

// AddBenefitDate adds v to the "benefit_date" field.
func (u *MiningProfitUnsoldUpsertBulk) AddBenefitDate(v uint32) *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.AddBenefitDate(v)
	})
}

// UpdateBenefitDate sets the "benefit_date" field to the value that was provided on create.
func (u *MiningProfitUnsoldUpsertBulk) UpdateBenefitDate() *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.UpdateBenefitDate()
	})
}

// ClearBenefitDate clears the value of the "benefit_date" field.
func (u *MiningProfitUnsoldUpsertBulk) ClearBenefitDate() *MiningProfitUnsoldUpsertBulk {
	return u.Update(func(s *MiningProfitUnsoldUpsert) {
		s.ClearBenefitDate()
	})
}

// Exec executes the query.
func (u *MiningProfitUnsoldUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MiningProfitUnsoldCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MiningProfitUnsoldCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MiningProfitUnsoldUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
