// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/ledger-manager/pkg/db/ent/miningprofitdetail"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// MiningProfitDetailCreate is the builder for creating a MiningProfitDetail entity.
type MiningProfitDetailCreate struct {
	config
	mutation *MiningProfitDetailMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (mpdc *MiningProfitDetailCreate) SetCreatedAt(u uint32) *MiningProfitDetailCreate {
	mpdc.mutation.SetCreatedAt(u)
	return mpdc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mpdc *MiningProfitDetailCreate) SetNillableCreatedAt(u *uint32) *MiningProfitDetailCreate {
	if u != nil {
		mpdc.SetCreatedAt(*u)
	}
	return mpdc
}

// SetUpdatedAt sets the "updated_at" field.
func (mpdc *MiningProfitDetailCreate) SetUpdatedAt(u uint32) *MiningProfitDetailCreate {
	mpdc.mutation.SetUpdatedAt(u)
	return mpdc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (mpdc *MiningProfitDetailCreate) SetNillableUpdatedAt(u *uint32) *MiningProfitDetailCreate {
	if u != nil {
		mpdc.SetUpdatedAt(*u)
	}
	return mpdc
}

// SetDeletedAt sets the "deleted_at" field.
func (mpdc *MiningProfitDetailCreate) SetDeletedAt(u uint32) *MiningProfitDetailCreate {
	mpdc.mutation.SetDeletedAt(u)
	return mpdc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (mpdc *MiningProfitDetailCreate) SetNillableDeletedAt(u *uint32) *MiningProfitDetailCreate {
	if u != nil {
		mpdc.SetDeletedAt(*u)
	}
	return mpdc
}

// SetGoodID sets the "good_id" field.
func (mpdc *MiningProfitDetailCreate) SetGoodID(u uuid.UUID) *MiningProfitDetailCreate {
	mpdc.mutation.SetGoodID(u)
	return mpdc
}

// SetNillableGoodID sets the "good_id" field if the given value is not nil.
func (mpdc *MiningProfitDetailCreate) SetNillableGoodID(u *uuid.UUID) *MiningProfitDetailCreate {
	if u != nil {
		mpdc.SetGoodID(*u)
	}
	return mpdc
}

// SetCoinTypeID sets the "coin_type_id" field.
func (mpdc *MiningProfitDetailCreate) SetCoinTypeID(u uuid.UUID) *MiningProfitDetailCreate {
	mpdc.mutation.SetCoinTypeID(u)
	return mpdc
}

// SetNillableCoinTypeID sets the "coin_type_id" field if the given value is not nil.
func (mpdc *MiningProfitDetailCreate) SetNillableCoinTypeID(u *uuid.UUID) *MiningProfitDetailCreate {
	if u != nil {
		mpdc.SetCoinTypeID(*u)
	}
	return mpdc
}

// SetAmount sets the "amount" field.
func (mpdc *MiningProfitDetailCreate) SetAmount(d decimal.Decimal) *MiningProfitDetailCreate {
	mpdc.mutation.SetAmount(d)
	return mpdc
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (mpdc *MiningProfitDetailCreate) SetNillableAmount(d *decimal.Decimal) *MiningProfitDetailCreate {
	if d != nil {
		mpdc.SetAmount(*d)
	}
	return mpdc
}

// SetBenefitDate sets the "benefit_date" field.
func (mpdc *MiningProfitDetailCreate) SetBenefitDate(u uint32) *MiningProfitDetailCreate {
	mpdc.mutation.SetBenefitDate(u)
	return mpdc
}

// SetNillableBenefitDate sets the "benefit_date" field if the given value is not nil.
func (mpdc *MiningProfitDetailCreate) SetNillableBenefitDate(u *uint32) *MiningProfitDetailCreate {
	if u != nil {
		mpdc.SetBenefitDate(*u)
	}
	return mpdc
}

// SetID sets the "id" field.
func (mpdc *MiningProfitDetailCreate) SetID(u uuid.UUID) *MiningProfitDetailCreate {
	mpdc.mutation.SetID(u)
	return mpdc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (mpdc *MiningProfitDetailCreate) SetNillableID(u *uuid.UUID) *MiningProfitDetailCreate {
	if u != nil {
		mpdc.SetID(*u)
	}
	return mpdc
}

// Mutation returns the MiningProfitDetailMutation object of the builder.
func (mpdc *MiningProfitDetailCreate) Mutation() *MiningProfitDetailMutation {
	return mpdc.mutation
}

// Save creates the MiningProfitDetail in the database.
func (mpdc *MiningProfitDetailCreate) Save(ctx context.Context) (*MiningProfitDetail, error) {
	var (
		err  error
		node *MiningProfitDetail
	)
	if err := mpdc.defaults(); err != nil {
		return nil, err
	}
	if len(mpdc.hooks) == 0 {
		if err = mpdc.check(); err != nil {
			return nil, err
		}
		node, err = mpdc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MiningProfitDetailMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mpdc.check(); err != nil {
				return nil, err
			}
			mpdc.mutation = mutation
			if node, err = mpdc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(mpdc.hooks) - 1; i >= 0; i-- {
			if mpdc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mpdc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, mpdc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*MiningProfitDetail)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from MiningProfitDetailMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mpdc *MiningProfitDetailCreate) SaveX(ctx context.Context) *MiningProfitDetail {
	v, err := mpdc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mpdc *MiningProfitDetailCreate) Exec(ctx context.Context) error {
	_, err := mpdc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpdc *MiningProfitDetailCreate) ExecX(ctx context.Context) {
	if err := mpdc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mpdc *MiningProfitDetailCreate) defaults() error {
	if _, ok := mpdc.mutation.CreatedAt(); !ok {
		if miningprofitdetail.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized miningprofitdetail.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := miningprofitdetail.DefaultCreatedAt()
		mpdc.mutation.SetCreatedAt(v)
	}
	if _, ok := mpdc.mutation.UpdatedAt(); !ok {
		if miningprofitdetail.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized miningprofitdetail.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := miningprofitdetail.DefaultUpdatedAt()
		mpdc.mutation.SetUpdatedAt(v)
	}
	if _, ok := mpdc.mutation.DeletedAt(); !ok {
		if miningprofitdetail.DefaultDeletedAt == nil {
			return fmt.Errorf("ent: uninitialized miningprofitdetail.DefaultDeletedAt (forgotten import ent/runtime?)")
		}
		v := miningprofitdetail.DefaultDeletedAt()
		mpdc.mutation.SetDeletedAt(v)
	}
	if _, ok := mpdc.mutation.GoodID(); !ok {
		if miningprofitdetail.DefaultGoodID == nil {
			return fmt.Errorf("ent: uninitialized miningprofitdetail.DefaultGoodID (forgotten import ent/runtime?)")
		}
		v := miningprofitdetail.DefaultGoodID()
		mpdc.mutation.SetGoodID(v)
	}
	if _, ok := mpdc.mutation.CoinTypeID(); !ok {
		if miningprofitdetail.DefaultCoinTypeID == nil {
			return fmt.Errorf("ent: uninitialized miningprofitdetail.DefaultCoinTypeID (forgotten import ent/runtime?)")
		}
		v := miningprofitdetail.DefaultCoinTypeID()
		mpdc.mutation.SetCoinTypeID(v)
	}
	if _, ok := mpdc.mutation.BenefitDate(); !ok {
		v := miningprofitdetail.DefaultBenefitDate
		mpdc.mutation.SetBenefitDate(v)
	}
	if _, ok := mpdc.mutation.ID(); !ok {
		if miningprofitdetail.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized miningprofitdetail.DefaultID (forgotten import ent/runtime?)")
		}
		v := miningprofitdetail.DefaultID()
		mpdc.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (mpdc *MiningProfitDetailCreate) check() error {
	if _, ok := mpdc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MiningProfitDetail.created_at"`)}
	}
	if _, ok := mpdc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MiningProfitDetail.updated_at"`)}
	}
	if _, ok := mpdc.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "MiningProfitDetail.deleted_at"`)}
	}
	return nil
}

func (mpdc *MiningProfitDetailCreate) sqlSave(ctx context.Context) (*MiningProfitDetail, error) {
	_node, _spec := mpdc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mpdc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (mpdc *MiningProfitDetailCreate) createSpec() (*MiningProfitDetail, *sqlgraph.CreateSpec) {
	var (
		_node = &MiningProfitDetail{config: mpdc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: miningprofitdetail.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: miningprofitdetail.FieldID,
			},
		}
	)
	_spec.OnConflict = mpdc.conflict
	if id, ok := mpdc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := mpdc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: miningprofitdetail.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := mpdc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: miningprofitdetail.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := mpdc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: miningprofitdetail.FieldDeletedAt,
		})
		_node.DeletedAt = value
	}
	if value, ok := mpdc.mutation.GoodID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: miningprofitdetail.FieldGoodID,
		})
		_node.GoodID = value
	}
	if value, ok := mpdc.mutation.CoinTypeID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: miningprofitdetail.FieldCoinTypeID,
		})
		_node.CoinTypeID = value
	}
	if value, ok := mpdc.mutation.Amount(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: miningprofitdetail.FieldAmount,
		})
		_node.Amount = value
	}
	if value, ok := mpdc.mutation.BenefitDate(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: miningprofitdetail.FieldBenefitDate,
		})
		_node.BenefitDate = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MiningProfitDetail.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MiningProfitDetailUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (mpdc *MiningProfitDetailCreate) OnConflict(opts ...sql.ConflictOption) *MiningProfitDetailUpsertOne {
	mpdc.conflict = opts
	return &MiningProfitDetailUpsertOne{
		create: mpdc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MiningProfitDetail.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (mpdc *MiningProfitDetailCreate) OnConflictColumns(columns ...string) *MiningProfitDetailUpsertOne {
	mpdc.conflict = append(mpdc.conflict, sql.ConflictColumns(columns...))
	return &MiningProfitDetailUpsertOne{
		create: mpdc,
	}
}

type (
	// MiningProfitDetailUpsertOne is the builder for "upsert"-ing
	//  one MiningProfitDetail node.
	MiningProfitDetailUpsertOne struct {
		create *MiningProfitDetailCreate
	}

	// MiningProfitDetailUpsert is the "OnConflict" setter.
	MiningProfitDetailUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *MiningProfitDetailUpsert) SetCreatedAt(v uint32) *MiningProfitDetailUpsert {
	u.Set(miningprofitdetail.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *MiningProfitDetailUpsert) UpdateCreatedAt() *MiningProfitDetailUpsert {
	u.SetExcluded(miningprofitdetail.FieldCreatedAt)
	return u
}

// AddCreatedAt adds v to the "created_at" field.
func (u *MiningProfitDetailUpsert) AddCreatedAt(v uint32) *MiningProfitDetailUpsert {
	u.Add(miningprofitdetail.FieldCreatedAt, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MiningProfitDetailUpsert) SetUpdatedAt(v uint32) *MiningProfitDetailUpsert {
	u.Set(miningprofitdetail.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MiningProfitDetailUpsert) UpdateUpdatedAt() *MiningProfitDetailUpsert {
	u.SetExcluded(miningprofitdetail.FieldUpdatedAt)
	return u
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *MiningProfitDetailUpsert) AddUpdatedAt(v uint32) *MiningProfitDetailUpsert {
	u.Add(miningprofitdetail.FieldUpdatedAt, v)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *MiningProfitDetailUpsert) SetDeletedAt(v uint32) *MiningProfitDetailUpsert {
	u.Set(miningprofitdetail.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *MiningProfitDetailUpsert) UpdateDeletedAt() *MiningProfitDetailUpsert {
	u.SetExcluded(miningprofitdetail.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *MiningProfitDetailUpsert) AddDeletedAt(v uint32) *MiningProfitDetailUpsert {
	u.Add(miningprofitdetail.FieldDeletedAt, v)
	return u
}

// SetGoodID sets the "good_id" field.
func (u *MiningProfitDetailUpsert) SetGoodID(v uuid.UUID) *MiningProfitDetailUpsert {
	u.Set(miningprofitdetail.FieldGoodID, v)
	return u
}

// UpdateGoodID sets the "good_id" field to the value that was provided on create.
func (u *MiningProfitDetailUpsert) UpdateGoodID() *MiningProfitDetailUpsert {
	u.SetExcluded(miningprofitdetail.FieldGoodID)
	return u
}

// ClearGoodID clears the value of the "good_id" field.
func (u *MiningProfitDetailUpsert) ClearGoodID() *MiningProfitDetailUpsert {
	u.SetNull(miningprofitdetail.FieldGoodID)
	return u
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *MiningProfitDetailUpsert) SetCoinTypeID(v uuid.UUID) *MiningProfitDetailUpsert {
	u.Set(miningprofitdetail.FieldCoinTypeID, v)
	return u
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *MiningProfitDetailUpsert) UpdateCoinTypeID() *MiningProfitDetailUpsert {
	u.SetExcluded(miningprofitdetail.FieldCoinTypeID)
	return u
}

// ClearCoinTypeID clears the value of the "coin_type_id" field.
func (u *MiningProfitDetailUpsert) ClearCoinTypeID() *MiningProfitDetailUpsert {
	u.SetNull(miningprofitdetail.FieldCoinTypeID)
	return u
}

// SetAmount sets the "amount" field.
func (u *MiningProfitDetailUpsert) SetAmount(v decimal.Decimal) *MiningProfitDetailUpsert {
	u.Set(miningprofitdetail.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *MiningProfitDetailUpsert) UpdateAmount() *MiningProfitDetailUpsert {
	u.SetExcluded(miningprofitdetail.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *MiningProfitDetailUpsert) AddAmount(v decimal.Decimal) *MiningProfitDetailUpsert {
	u.Add(miningprofitdetail.FieldAmount, v)
	return u
}

// ClearAmount clears the value of the "amount" field.
func (u *MiningProfitDetailUpsert) ClearAmount() *MiningProfitDetailUpsert {
	u.SetNull(miningprofitdetail.FieldAmount)
	return u
}

// SetBenefitDate sets the "benefit_date" field.
func (u *MiningProfitDetailUpsert) SetBenefitDate(v uint32) *MiningProfitDetailUpsert {
	u.Set(miningprofitdetail.FieldBenefitDate, v)
	return u
}

// UpdateBenefitDate sets the "benefit_date" field to the value that was provided on create.
func (u *MiningProfitDetailUpsert) UpdateBenefitDate() *MiningProfitDetailUpsert {
	u.SetExcluded(miningprofitdetail.FieldBenefitDate)
	return u
}

// AddBenefitDate adds v to the "benefit_date" field.
func (u *MiningProfitDetailUpsert) AddBenefitDate(v uint32) *MiningProfitDetailUpsert {
	u.Add(miningprofitdetail.FieldBenefitDate, v)
	return u
}

// ClearBenefitDate clears the value of the "benefit_date" field.
func (u *MiningProfitDetailUpsert) ClearBenefitDate() *MiningProfitDetailUpsert {
	u.SetNull(miningprofitdetail.FieldBenefitDate)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.MiningProfitDetail.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(miningprofitdetail.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *MiningProfitDetailUpsertOne) UpdateNewValues() *MiningProfitDetailUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(miningprofitdetail.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.MiningProfitDetail.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *MiningProfitDetailUpsertOne) Ignore() *MiningProfitDetailUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MiningProfitDetailUpsertOne) DoNothing() *MiningProfitDetailUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MiningProfitDetailCreate.OnConflict
// documentation for more info.
func (u *MiningProfitDetailUpsertOne) Update(set func(*MiningProfitDetailUpsert)) *MiningProfitDetailUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MiningProfitDetailUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *MiningProfitDetailUpsertOne) SetCreatedAt(v uint32) *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *MiningProfitDetailUpsertOne) AddCreatedAt(v uint32) *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *MiningProfitDetailUpsertOne) UpdateCreatedAt() *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MiningProfitDetailUpsertOne) SetUpdatedAt(v uint32) *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *MiningProfitDetailUpsertOne) AddUpdatedAt(v uint32) *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MiningProfitDetailUpsertOne) UpdateUpdatedAt() *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *MiningProfitDetailUpsertOne) SetDeletedAt(v uint32) *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *MiningProfitDetailUpsertOne) AddDeletedAt(v uint32) *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *MiningProfitDetailUpsertOne) UpdateDeletedAt() *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetGoodID sets the "good_id" field.
func (u *MiningProfitDetailUpsertOne) SetGoodID(v uuid.UUID) *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.SetGoodID(v)
	})
}

// UpdateGoodID sets the "good_id" field to the value that was provided on create.
func (u *MiningProfitDetailUpsertOne) UpdateGoodID() *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.UpdateGoodID()
	})
}

// ClearGoodID clears the value of the "good_id" field.
func (u *MiningProfitDetailUpsertOne) ClearGoodID() *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.ClearGoodID()
	})
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *MiningProfitDetailUpsertOne) SetCoinTypeID(v uuid.UUID) *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.SetCoinTypeID(v)
	})
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *MiningProfitDetailUpsertOne) UpdateCoinTypeID() *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.UpdateCoinTypeID()
	})
}

// ClearCoinTypeID clears the value of the "coin_type_id" field.
func (u *MiningProfitDetailUpsertOne) ClearCoinTypeID() *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.ClearCoinTypeID()
	})
}

// SetAmount sets the "amount" field.
func (u *MiningProfitDetailUpsertOne) SetAmount(v decimal.Decimal) *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *MiningProfitDetailUpsertOne) AddAmount(v decimal.Decimal) *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *MiningProfitDetailUpsertOne) UpdateAmount() *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.UpdateAmount()
	})
}

// ClearAmount clears the value of the "amount" field.
func (u *MiningProfitDetailUpsertOne) ClearAmount() *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.ClearAmount()
	})
}

// SetBenefitDate sets the "benefit_date" field.
func (u *MiningProfitDetailUpsertOne) SetBenefitDate(v uint32) *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.SetBenefitDate(v)
	})
}

// AddBenefitDate adds v to the "benefit_date" field.
func (u *MiningProfitDetailUpsertOne) AddBenefitDate(v uint32) *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.AddBenefitDate(v)
	})
}

// UpdateBenefitDate sets the "benefit_date" field to the value that was provided on create.
func (u *MiningProfitDetailUpsertOne) UpdateBenefitDate() *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.UpdateBenefitDate()
	})
}

// ClearBenefitDate clears the value of the "benefit_date" field.
func (u *MiningProfitDetailUpsertOne) ClearBenefitDate() *MiningProfitDetailUpsertOne {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.ClearBenefitDate()
	})
}

// Exec executes the query.
func (u *MiningProfitDetailUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MiningProfitDetailCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MiningProfitDetailUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MiningProfitDetailUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: MiningProfitDetailUpsertOne.ID is not supported by MySQL driver. Use MiningProfitDetailUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MiningProfitDetailUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MiningProfitDetailCreateBulk is the builder for creating many MiningProfitDetail entities in bulk.
type MiningProfitDetailCreateBulk struct {
	config
	builders []*MiningProfitDetailCreate
	conflict []sql.ConflictOption
}

// Save creates the MiningProfitDetail entities in the database.
func (mpdcb *MiningProfitDetailCreateBulk) Save(ctx context.Context) ([]*MiningProfitDetail, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mpdcb.builders))
	nodes := make([]*MiningProfitDetail, len(mpdcb.builders))
	mutators := make([]Mutator, len(mpdcb.builders))
	for i := range mpdcb.builders {
		func(i int, root context.Context) {
			builder := mpdcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MiningProfitDetailMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mpdcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = mpdcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mpdcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mpdcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mpdcb *MiningProfitDetailCreateBulk) SaveX(ctx context.Context) []*MiningProfitDetail {
	v, err := mpdcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mpdcb *MiningProfitDetailCreateBulk) Exec(ctx context.Context) error {
	_, err := mpdcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpdcb *MiningProfitDetailCreateBulk) ExecX(ctx context.Context) {
	if err := mpdcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MiningProfitDetail.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MiningProfitDetailUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (mpdcb *MiningProfitDetailCreateBulk) OnConflict(opts ...sql.ConflictOption) *MiningProfitDetailUpsertBulk {
	mpdcb.conflict = opts
	return &MiningProfitDetailUpsertBulk{
		create: mpdcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MiningProfitDetail.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (mpdcb *MiningProfitDetailCreateBulk) OnConflictColumns(columns ...string) *MiningProfitDetailUpsertBulk {
	mpdcb.conflict = append(mpdcb.conflict, sql.ConflictColumns(columns...))
	return &MiningProfitDetailUpsertBulk{
		create: mpdcb,
	}
}

// MiningProfitDetailUpsertBulk is the builder for "upsert"-ing
// a bulk of MiningProfitDetail nodes.
type MiningProfitDetailUpsertBulk struct {
	create *MiningProfitDetailCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MiningProfitDetail.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(miningprofitdetail.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *MiningProfitDetailUpsertBulk) UpdateNewValues() *MiningProfitDetailUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(miningprofitdetail.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MiningProfitDetail.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *MiningProfitDetailUpsertBulk) Ignore() *MiningProfitDetailUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MiningProfitDetailUpsertBulk) DoNothing() *MiningProfitDetailUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MiningProfitDetailCreateBulk.OnConflict
// documentation for more info.
func (u *MiningProfitDetailUpsertBulk) Update(set func(*MiningProfitDetailUpsert)) *MiningProfitDetailUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MiningProfitDetailUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *MiningProfitDetailUpsertBulk) SetCreatedAt(v uint32) *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *MiningProfitDetailUpsertBulk) AddCreatedAt(v uint32) *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *MiningProfitDetailUpsertBulk) UpdateCreatedAt() *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MiningProfitDetailUpsertBulk) SetUpdatedAt(v uint32) *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *MiningProfitDetailUpsertBulk) AddUpdatedAt(v uint32) *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MiningProfitDetailUpsertBulk) UpdateUpdatedAt() *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *MiningProfitDetailUpsertBulk) SetDeletedAt(v uint32) *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *MiningProfitDetailUpsertBulk) AddDeletedAt(v uint32) *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *MiningProfitDetailUpsertBulk) UpdateDeletedAt() *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetGoodID sets the "good_id" field.
func (u *MiningProfitDetailUpsertBulk) SetGoodID(v uuid.UUID) *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.SetGoodID(v)
	})
}

// UpdateGoodID sets the "good_id" field to the value that was provided on create.
func (u *MiningProfitDetailUpsertBulk) UpdateGoodID() *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.UpdateGoodID()
	})
}

// ClearGoodID clears the value of the "good_id" field.
func (u *MiningProfitDetailUpsertBulk) ClearGoodID() *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.ClearGoodID()
	})
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *MiningProfitDetailUpsertBulk) SetCoinTypeID(v uuid.UUID) *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.SetCoinTypeID(v)
	})
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *MiningProfitDetailUpsertBulk) UpdateCoinTypeID() *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.UpdateCoinTypeID()
	})
}

// ClearCoinTypeID clears the value of the "coin_type_id" field.
func (u *MiningProfitDetailUpsertBulk) ClearCoinTypeID() *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.ClearCoinTypeID()
	})
}

// SetAmount sets the "amount" field.
func (u *MiningProfitDetailUpsertBulk) SetAmount(v decimal.Decimal) *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *MiningProfitDetailUpsertBulk) AddAmount(v decimal.Decimal) *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *MiningProfitDetailUpsertBulk) UpdateAmount() *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.UpdateAmount()
	})
}

// ClearAmount clears the value of the "amount" field.
func (u *MiningProfitDetailUpsertBulk) ClearAmount() *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.ClearAmount()
	})
}

// SetBenefitDate sets the "benefit_date" field.
func (u *MiningProfitDetailUpsertBulk) SetBenefitDate(v uint32) *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.SetBenefitDate(v)
	})
}

// AddBenefitDate adds v to the "benefit_date" field.
func (u *MiningProfitDetailUpsertBulk) AddBenefitDate(v uint32) *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.AddBenefitDate(v)
	})
}

// UpdateBenefitDate sets the "benefit_date" field to the value that was provided on create.
func (u *MiningProfitDetailUpsertBulk) UpdateBenefitDate() *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.UpdateBenefitDate()
	})
}

// ClearBenefitDate clears the value of the "benefit_date" field.
func (u *MiningProfitDetailUpsertBulk) ClearBenefitDate() *MiningProfitDetailUpsertBulk {
	return u.Update(func(s *MiningProfitDetailUpsert) {
		s.ClearBenefitDate()
	})
}

// Exec executes the query.
func (u *MiningProfitDetailUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MiningProfitDetailCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MiningProfitDetailCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MiningProfitDetailUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
