// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/ledger-manager/pkg/db/ent/miningprofitunsold"
	"github.com/NpoolPlatform/ledger-manager/pkg/db/ent/predicate"
)

// MiningProfitUnsoldDelete is the builder for deleting a MiningProfitUnsold entity.
type MiningProfitUnsoldDelete struct {
	config
	hooks    []Hook
	mutation *MiningProfitUnsoldMutation
}

// Where appends a list predicates to the MiningProfitUnsoldDelete builder.
func (mpud *MiningProfitUnsoldDelete) Where(ps ...predicate.MiningProfitUnsold) *MiningProfitUnsoldDelete {
	mpud.mutation.Where(ps...)
	return mpud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mpud *MiningProfitUnsoldDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mpud.hooks) == 0 {
		affected, err = mpud.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MiningProfitUnsoldMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mpud.mutation = mutation
			affected, err = mpud.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mpud.hooks) - 1; i >= 0; i-- {
			if mpud.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mpud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mpud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpud *MiningProfitUnsoldDelete) ExecX(ctx context.Context) int {
	n, err := mpud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mpud *MiningProfitUnsoldDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: miningprofitunsold.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: miningprofitunsold.FieldID,
			},
		},
	}
	if ps := mpud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mpud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// MiningProfitUnsoldDeleteOne is the builder for deleting a single MiningProfitUnsold entity.
type MiningProfitUnsoldDeleteOne struct {
	mpud *MiningProfitUnsoldDelete
}

// Exec executes the deletion query.
func (mpudo *MiningProfitUnsoldDeleteOne) Exec(ctx context.Context) error {
	n, err := mpudo.mpud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{miningprofitunsold.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mpudo *MiningProfitUnsoldDeleteOne) ExecX(ctx context.Context) {
	mpudo.mpud.ExecX(ctx)
}
