// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/ledger-manager/pkg/db/ent/miningprofitgeneral"
	"github.com/NpoolPlatform/ledger-manager/pkg/db/ent/predicate"
)

// MiningProfitGeneralDelete is the builder for deleting a MiningProfitGeneral entity.
type MiningProfitGeneralDelete struct {
	config
	hooks    []Hook
	mutation *MiningProfitGeneralMutation
}

// Where appends a list predicates to the MiningProfitGeneralDelete builder.
func (mpgd *MiningProfitGeneralDelete) Where(ps ...predicate.MiningProfitGeneral) *MiningProfitGeneralDelete {
	mpgd.mutation.Where(ps...)
	return mpgd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mpgd *MiningProfitGeneralDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mpgd.hooks) == 0 {
		affected, err = mpgd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MiningProfitGeneralMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mpgd.mutation = mutation
			affected, err = mpgd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mpgd.hooks) - 1; i >= 0; i-- {
			if mpgd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mpgd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mpgd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpgd *MiningProfitGeneralDelete) ExecX(ctx context.Context) int {
	n, err := mpgd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mpgd *MiningProfitGeneralDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: miningprofitgeneral.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: miningprofitgeneral.FieldID,
			},
		},
	}
	if ps := mpgd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mpgd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// MiningProfitGeneralDeleteOne is the builder for deleting a single MiningProfitGeneral entity.
type MiningProfitGeneralDeleteOne struct {
	mpgd *MiningProfitGeneralDelete
}

// Exec executes the deletion query.
func (mpgdo *MiningProfitGeneralDeleteOne) Exec(ctx context.Context) error {
	n, err := mpgdo.mpgd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{miningprofitgeneral.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mpgdo *MiningProfitGeneralDeleteOne) ExecX(ctx context.Context) {
	mpgdo.mpgd.ExecX(ctx)
}
