// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/ledger-manager/pkg/db/ent/miningprofitgeneral"
	"github.com/NpoolPlatform/ledger-manager/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// MiningProfitGeneralQuery is the builder for querying MiningProfitGeneral entities.
type MiningProfitGeneralQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.MiningProfitGeneral
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MiningProfitGeneralQuery builder.
func (mpgq *MiningProfitGeneralQuery) Where(ps ...predicate.MiningProfitGeneral) *MiningProfitGeneralQuery {
	mpgq.predicates = append(mpgq.predicates, ps...)
	return mpgq
}

// Limit adds a limit step to the query.
func (mpgq *MiningProfitGeneralQuery) Limit(limit int) *MiningProfitGeneralQuery {
	mpgq.limit = &limit
	return mpgq
}

// Offset adds an offset step to the query.
func (mpgq *MiningProfitGeneralQuery) Offset(offset int) *MiningProfitGeneralQuery {
	mpgq.offset = &offset
	return mpgq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mpgq *MiningProfitGeneralQuery) Unique(unique bool) *MiningProfitGeneralQuery {
	mpgq.unique = &unique
	return mpgq
}

// Order adds an order step to the query.
func (mpgq *MiningProfitGeneralQuery) Order(o ...OrderFunc) *MiningProfitGeneralQuery {
	mpgq.order = append(mpgq.order, o...)
	return mpgq
}

// First returns the first MiningProfitGeneral entity from the query.
// Returns a *NotFoundError when no MiningProfitGeneral was found.
func (mpgq *MiningProfitGeneralQuery) First(ctx context.Context) (*MiningProfitGeneral, error) {
	nodes, err := mpgq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{miningprofitgeneral.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mpgq *MiningProfitGeneralQuery) FirstX(ctx context.Context) *MiningProfitGeneral {
	node, err := mpgq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MiningProfitGeneral ID from the query.
// Returns a *NotFoundError when no MiningProfitGeneral ID was found.
func (mpgq *MiningProfitGeneralQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = mpgq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{miningprofitgeneral.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mpgq *MiningProfitGeneralQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := mpgq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MiningProfitGeneral entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MiningProfitGeneral entity is found.
// Returns a *NotFoundError when no MiningProfitGeneral entities are found.
func (mpgq *MiningProfitGeneralQuery) Only(ctx context.Context) (*MiningProfitGeneral, error) {
	nodes, err := mpgq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{miningprofitgeneral.Label}
	default:
		return nil, &NotSingularError{miningprofitgeneral.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mpgq *MiningProfitGeneralQuery) OnlyX(ctx context.Context) *MiningProfitGeneral {
	node, err := mpgq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MiningProfitGeneral ID in the query.
// Returns a *NotSingularError when more than one MiningProfitGeneral ID is found.
// Returns a *NotFoundError when no entities are found.
func (mpgq *MiningProfitGeneralQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = mpgq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{miningprofitgeneral.Label}
	default:
		err = &NotSingularError{miningprofitgeneral.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mpgq *MiningProfitGeneralQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := mpgq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MiningProfitGenerals.
func (mpgq *MiningProfitGeneralQuery) All(ctx context.Context) ([]*MiningProfitGeneral, error) {
	if err := mpgq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return mpgq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (mpgq *MiningProfitGeneralQuery) AllX(ctx context.Context) []*MiningProfitGeneral {
	nodes, err := mpgq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MiningProfitGeneral IDs.
func (mpgq *MiningProfitGeneralQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := mpgq.Select(miningprofitgeneral.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mpgq *MiningProfitGeneralQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := mpgq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mpgq *MiningProfitGeneralQuery) Count(ctx context.Context) (int, error) {
	if err := mpgq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return mpgq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (mpgq *MiningProfitGeneralQuery) CountX(ctx context.Context) int {
	count, err := mpgq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mpgq *MiningProfitGeneralQuery) Exist(ctx context.Context) (bool, error) {
	if err := mpgq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return mpgq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (mpgq *MiningProfitGeneralQuery) ExistX(ctx context.Context) bool {
	exist, err := mpgq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MiningProfitGeneralQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mpgq *MiningProfitGeneralQuery) Clone() *MiningProfitGeneralQuery {
	if mpgq == nil {
		return nil
	}
	return &MiningProfitGeneralQuery{
		config:     mpgq.config,
		limit:      mpgq.limit,
		offset:     mpgq.offset,
		order:      append([]OrderFunc{}, mpgq.order...),
		predicates: append([]predicate.MiningProfitGeneral{}, mpgq.predicates...),
		// clone intermediate query.
		sql:    mpgq.sql.Clone(),
		path:   mpgq.path,
		unique: mpgq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MiningProfitGeneral.Query().
//		GroupBy(miningprofitgeneral.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (mpgq *MiningProfitGeneralQuery) GroupBy(field string, fields ...string) *MiningProfitGeneralGroupBy {
	grbuild := &MiningProfitGeneralGroupBy{config: mpgq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := mpgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return mpgq.sqlQuery(ctx), nil
	}
	grbuild.label = miningprofitgeneral.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.MiningProfitGeneral.Query().
//		Select(miningprofitgeneral.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (mpgq *MiningProfitGeneralQuery) Select(fields ...string) *MiningProfitGeneralSelect {
	mpgq.fields = append(mpgq.fields, fields...)
	selbuild := &MiningProfitGeneralSelect{MiningProfitGeneralQuery: mpgq}
	selbuild.label = miningprofitgeneral.Label
	selbuild.flds, selbuild.scan = &mpgq.fields, selbuild.Scan
	return selbuild
}

func (mpgq *MiningProfitGeneralQuery) prepareQuery(ctx context.Context) error {
	for _, f := range mpgq.fields {
		if !miningprofitgeneral.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mpgq.path != nil {
		prev, err := mpgq.path(ctx)
		if err != nil {
			return err
		}
		mpgq.sql = prev
	}
	if miningprofitgeneral.Policy == nil {
		return errors.New("ent: uninitialized miningprofitgeneral.Policy (forgotten import ent/runtime?)")
	}
	if err := miningprofitgeneral.Policy.EvalQuery(ctx, mpgq); err != nil {
		return err
	}
	return nil
}

func (mpgq *MiningProfitGeneralQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MiningProfitGeneral, error) {
	var (
		nodes = []*MiningProfitGeneral{}
		_spec = mpgq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*MiningProfitGeneral).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &MiningProfitGeneral{config: mpgq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(mpgq.modifiers) > 0 {
		_spec.Modifiers = mpgq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mpgq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mpgq *MiningProfitGeneralQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mpgq.querySpec()
	if len(mpgq.modifiers) > 0 {
		_spec.Modifiers = mpgq.modifiers
	}
	_spec.Node.Columns = mpgq.fields
	if len(mpgq.fields) > 0 {
		_spec.Unique = mpgq.unique != nil && *mpgq.unique
	}
	return sqlgraph.CountNodes(ctx, mpgq.driver, _spec)
}

func (mpgq *MiningProfitGeneralQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := mpgq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (mpgq *MiningProfitGeneralQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   miningprofitgeneral.Table,
			Columns: miningprofitgeneral.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: miningprofitgeneral.FieldID,
			},
		},
		From:   mpgq.sql,
		Unique: true,
	}
	if unique := mpgq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := mpgq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, miningprofitgeneral.FieldID)
		for i := range fields {
			if fields[i] != miningprofitgeneral.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mpgq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mpgq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mpgq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mpgq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mpgq *MiningProfitGeneralQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mpgq.driver.Dialect())
	t1 := builder.Table(miningprofitgeneral.Table)
	columns := mpgq.fields
	if len(columns) == 0 {
		columns = miningprofitgeneral.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mpgq.sql != nil {
		selector = mpgq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mpgq.unique != nil && *mpgq.unique {
		selector.Distinct()
	}
	for _, m := range mpgq.modifiers {
		m(selector)
	}
	for _, p := range mpgq.predicates {
		p(selector)
	}
	for _, p := range mpgq.order {
		p(selector)
	}
	if offset := mpgq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mpgq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (mpgq *MiningProfitGeneralQuery) ForUpdate(opts ...sql.LockOption) *MiningProfitGeneralQuery {
	if mpgq.driver.Dialect() == dialect.Postgres {
		mpgq.Unique(false)
	}
	mpgq.modifiers = append(mpgq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return mpgq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (mpgq *MiningProfitGeneralQuery) ForShare(opts ...sql.LockOption) *MiningProfitGeneralQuery {
	if mpgq.driver.Dialect() == dialect.Postgres {
		mpgq.Unique(false)
	}
	mpgq.modifiers = append(mpgq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return mpgq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (mpgq *MiningProfitGeneralQuery) Modify(modifiers ...func(s *sql.Selector)) *MiningProfitGeneralSelect {
	mpgq.modifiers = append(mpgq.modifiers, modifiers...)
	return mpgq.Select()
}

// MiningProfitGeneralGroupBy is the group-by builder for MiningProfitGeneral entities.
type MiningProfitGeneralGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mpggb *MiningProfitGeneralGroupBy) Aggregate(fns ...AggregateFunc) *MiningProfitGeneralGroupBy {
	mpggb.fns = append(mpggb.fns, fns...)
	return mpggb
}

// Scan applies the group-by query and scans the result into the given value.
func (mpggb *MiningProfitGeneralGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := mpggb.path(ctx)
	if err != nil {
		return err
	}
	mpggb.sql = query
	return mpggb.sqlScan(ctx, v)
}

func (mpggb *MiningProfitGeneralGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range mpggb.fields {
		if !miningprofitgeneral.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := mpggb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mpggb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (mpggb *MiningProfitGeneralGroupBy) sqlQuery() *sql.Selector {
	selector := mpggb.sql.Select()
	aggregation := make([]string, 0, len(mpggb.fns))
	for _, fn := range mpggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(mpggb.fields)+len(mpggb.fns))
		for _, f := range mpggb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(mpggb.fields...)...)
}

// MiningProfitGeneralSelect is the builder for selecting fields of MiningProfitGeneral entities.
type MiningProfitGeneralSelect struct {
	*MiningProfitGeneralQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (mpgs *MiningProfitGeneralSelect) Scan(ctx context.Context, v interface{}) error {
	if err := mpgs.prepareQuery(ctx); err != nil {
		return err
	}
	mpgs.sql = mpgs.MiningProfitGeneralQuery.sqlQuery(ctx)
	return mpgs.sqlScan(ctx, v)
}

func (mpgs *MiningProfitGeneralSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := mpgs.sql.Query()
	if err := mpgs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (mpgs *MiningProfitGeneralSelect) Modify(modifiers ...func(s *sql.Selector)) *MiningProfitGeneralSelect {
	mpgs.modifiers = append(mpgs.modifiers, modifiers...)
	return mpgs
}
