// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/ledger-manager/pkg/db/ent/miningprofitunsold"
	"github.com/NpoolPlatform/ledger-manager/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// MiningProfitUnsoldQuery is the builder for querying MiningProfitUnsold entities.
type MiningProfitUnsoldQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.MiningProfitUnsold
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MiningProfitUnsoldQuery builder.
func (mpuq *MiningProfitUnsoldQuery) Where(ps ...predicate.MiningProfitUnsold) *MiningProfitUnsoldQuery {
	mpuq.predicates = append(mpuq.predicates, ps...)
	return mpuq
}

// Limit adds a limit step to the query.
func (mpuq *MiningProfitUnsoldQuery) Limit(limit int) *MiningProfitUnsoldQuery {
	mpuq.limit = &limit
	return mpuq
}

// Offset adds an offset step to the query.
func (mpuq *MiningProfitUnsoldQuery) Offset(offset int) *MiningProfitUnsoldQuery {
	mpuq.offset = &offset
	return mpuq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mpuq *MiningProfitUnsoldQuery) Unique(unique bool) *MiningProfitUnsoldQuery {
	mpuq.unique = &unique
	return mpuq
}

// Order adds an order step to the query.
func (mpuq *MiningProfitUnsoldQuery) Order(o ...OrderFunc) *MiningProfitUnsoldQuery {
	mpuq.order = append(mpuq.order, o...)
	return mpuq
}

// First returns the first MiningProfitUnsold entity from the query.
// Returns a *NotFoundError when no MiningProfitUnsold was found.
func (mpuq *MiningProfitUnsoldQuery) First(ctx context.Context) (*MiningProfitUnsold, error) {
	nodes, err := mpuq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{miningprofitunsold.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mpuq *MiningProfitUnsoldQuery) FirstX(ctx context.Context) *MiningProfitUnsold {
	node, err := mpuq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MiningProfitUnsold ID from the query.
// Returns a *NotFoundError when no MiningProfitUnsold ID was found.
func (mpuq *MiningProfitUnsoldQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = mpuq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{miningprofitunsold.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mpuq *MiningProfitUnsoldQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := mpuq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MiningProfitUnsold entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MiningProfitUnsold entity is found.
// Returns a *NotFoundError when no MiningProfitUnsold entities are found.
func (mpuq *MiningProfitUnsoldQuery) Only(ctx context.Context) (*MiningProfitUnsold, error) {
	nodes, err := mpuq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{miningprofitunsold.Label}
	default:
		return nil, &NotSingularError{miningprofitunsold.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mpuq *MiningProfitUnsoldQuery) OnlyX(ctx context.Context) *MiningProfitUnsold {
	node, err := mpuq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MiningProfitUnsold ID in the query.
// Returns a *NotSingularError when more than one MiningProfitUnsold ID is found.
// Returns a *NotFoundError when no entities are found.
func (mpuq *MiningProfitUnsoldQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = mpuq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{miningprofitunsold.Label}
	default:
		err = &NotSingularError{miningprofitunsold.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mpuq *MiningProfitUnsoldQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := mpuq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MiningProfitUnsolds.
func (mpuq *MiningProfitUnsoldQuery) All(ctx context.Context) ([]*MiningProfitUnsold, error) {
	if err := mpuq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return mpuq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (mpuq *MiningProfitUnsoldQuery) AllX(ctx context.Context) []*MiningProfitUnsold {
	nodes, err := mpuq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MiningProfitUnsold IDs.
func (mpuq *MiningProfitUnsoldQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := mpuq.Select(miningprofitunsold.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mpuq *MiningProfitUnsoldQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := mpuq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mpuq *MiningProfitUnsoldQuery) Count(ctx context.Context) (int, error) {
	if err := mpuq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return mpuq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (mpuq *MiningProfitUnsoldQuery) CountX(ctx context.Context) int {
	count, err := mpuq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mpuq *MiningProfitUnsoldQuery) Exist(ctx context.Context) (bool, error) {
	if err := mpuq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return mpuq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (mpuq *MiningProfitUnsoldQuery) ExistX(ctx context.Context) bool {
	exist, err := mpuq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MiningProfitUnsoldQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mpuq *MiningProfitUnsoldQuery) Clone() *MiningProfitUnsoldQuery {
	if mpuq == nil {
		return nil
	}
	return &MiningProfitUnsoldQuery{
		config:     mpuq.config,
		limit:      mpuq.limit,
		offset:     mpuq.offset,
		order:      append([]OrderFunc{}, mpuq.order...),
		predicates: append([]predicate.MiningProfitUnsold{}, mpuq.predicates...),
		// clone intermediate query.
		sql:    mpuq.sql.Clone(),
		path:   mpuq.path,
		unique: mpuq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MiningProfitUnsold.Query().
//		GroupBy(miningprofitunsold.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (mpuq *MiningProfitUnsoldQuery) GroupBy(field string, fields ...string) *MiningProfitUnsoldGroupBy {
	grbuild := &MiningProfitUnsoldGroupBy{config: mpuq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := mpuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return mpuq.sqlQuery(ctx), nil
	}
	grbuild.label = miningprofitunsold.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.MiningProfitUnsold.Query().
//		Select(miningprofitunsold.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (mpuq *MiningProfitUnsoldQuery) Select(fields ...string) *MiningProfitUnsoldSelect {
	mpuq.fields = append(mpuq.fields, fields...)
	selbuild := &MiningProfitUnsoldSelect{MiningProfitUnsoldQuery: mpuq}
	selbuild.label = miningprofitunsold.Label
	selbuild.flds, selbuild.scan = &mpuq.fields, selbuild.Scan
	return selbuild
}

func (mpuq *MiningProfitUnsoldQuery) prepareQuery(ctx context.Context) error {
	for _, f := range mpuq.fields {
		if !miningprofitunsold.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mpuq.path != nil {
		prev, err := mpuq.path(ctx)
		if err != nil {
			return err
		}
		mpuq.sql = prev
	}
	if miningprofitunsold.Policy == nil {
		return errors.New("ent: uninitialized miningprofitunsold.Policy (forgotten import ent/runtime?)")
	}
	if err := miningprofitunsold.Policy.EvalQuery(ctx, mpuq); err != nil {
		return err
	}
	return nil
}

func (mpuq *MiningProfitUnsoldQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MiningProfitUnsold, error) {
	var (
		nodes = []*MiningProfitUnsold{}
		_spec = mpuq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*MiningProfitUnsold).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &MiningProfitUnsold{config: mpuq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(mpuq.modifiers) > 0 {
		_spec.Modifiers = mpuq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mpuq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mpuq *MiningProfitUnsoldQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mpuq.querySpec()
	if len(mpuq.modifiers) > 0 {
		_spec.Modifiers = mpuq.modifiers
	}
	_spec.Node.Columns = mpuq.fields
	if len(mpuq.fields) > 0 {
		_spec.Unique = mpuq.unique != nil && *mpuq.unique
	}
	return sqlgraph.CountNodes(ctx, mpuq.driver, _spec)
}

func (mpuq *MiningProfitUnsoldQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := mpuq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (mpuq *MiningProfitUnsoldQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   miningprofitunsold.Table,
			Columns: miningprofitunsold.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: miningprofitunsold.FieldID,
			},
		},
		From:   mpuq.sql,
		Unique: true,
	}
	if unique := mpuq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := mpuq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, miningprofitunsold.FieldID)
		for i := range fields {
			if fields[i] != miningprofitunsold.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mpuq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mpuq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mpuq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mpuq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mpuq *MiningProfitUnsoldQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mpuq.driver.Dialect())
	t1 := builder.Table(miningprofitunsold.Table)
	columns := mpuq.fields
	if len(columns) == 0 {
		columns = miningprofitunsold.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mpuq.sql != nil {
		selector = mpuq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mpuq.unique != nil && *mpuq.unique {
		selector.Distinct()
	}
	for _, m := range mpuq.modifiers {
		m(selector)
	}
	for _, p := range mpuq.predicates {
		p(selector)
	}
	for _, p := range mpuq.order {
		p(selector)
	}
	if offset := mpuq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mpuq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (mpuq *MiningProfitUnsoldQuery) ForUpdate(opts ...sql.LockOption) *MiningProfitUnsoldQuery {
	if mpuq.driver.Dialect() == dialect.Postgres {
		mpuq.Unique(false)
	}
	mpuq.modifiers = append(mpuq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return mpuq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (mpuq *MiningProfitUnsoldQuery) ForShare(opts ...sql.LockOption) *MiningProfitUnsoldQuery {
	if mpuq.driver.Dialect() == dialect.Postgres {
		mpuq.Unique(false)
	}
	mpuq.modifiers = append(mpuq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return mpuq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (mpuq *MiningProfitUnsoldQuery) Modify(modifiers ...func(s *sql.Selector)) *MiningProfitUnsoldSelect {
	mpuq.modifiers = append(mpuq.modifiers, modifiers...)
	return mpuq.Select()
}

// MiningProfitUnsoldGroupBy is the group-by builder for MiningProfitUnsold entities.
type MiningProfitUnsoldGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mpugb *MiningProfitUnsoldGroupBy) Aggregate(fns ...AggregateFunc) *MiningProfitUnsoldGroupBy {
	mpugb.fns = append(mpugb.fns, fns...)
	return mpugb
}

// Scan applies the group-by query and scans the result into the given value.
func (mpugb *MiningProfitUnsoldGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := mpugb.path(ctx)
	if err != nil {
		return err
	}
	mpugb.sql = query
	return mpugb.sqlScan(ctx, v)
}

func (mpugb *MiningProfitUnsoldGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range mpugb.fields {
		if !miningprofitunsold.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := mpugb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mpugb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (mpugb *MiningProfitUnsoldGroupBy) sqlQuery() *sql.Selector {
	selector := mpugb.sql.Select()
	aggregation := make([]string, 0, len(mpugb.fns))
	for _, fn := range mpugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(mpugb.fields)+len(mpugb.fns))
		for _, f := range mpugb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(mpugb.fields...)...)
}

// MiningProfitUnsoldSelect is the builder for selecting fields of MiningProfitUnsold entities.
type MiningProfitUnsoldSelect struct {
	*MiningProfitUnsoldQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (mpus *MiningProfitUnsoldSelect) Scan(ctx context.Context, v interface{}) error {
	if err := mpus.prepareQuery(ctx); err != nil {
		return err
	}
	mpus.sql = mpus.MiningProfitUnsoldQuery.sqlQuery(ctx)
	return mpus.sqlScan(ctx, v)
}

func (mpus *MiningProfitUnsoldSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := mpus.sql.Query()
	if err := mpus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (mpus *MiningProfitUnsoldSelect) Modify(modifiers ...func(s *sql.Selector)) *MiningProfitUnsoldSelect {
	mpus.modifiers = append(mpus.modifiers, modifiers...)
	return mpus
}
