// Code generated by ent, DO NOT EDIT.

package privacy

import (
	"context"
	"fmt"

	"github.com/NpoolPlatform/ledger-manager/pkg/db/ent"

	"entgo.io/ent/entql"
	"entgo.io/ent/privacy"
)

var (
	// Allow may be returned by rules to indicate that the policy
	// evaluation should terminate with allow decision.
	Allow = privacy.Allow

	// Deny may be returned by rules to indicate that the policy
	// evaluation should terminate with deny decision.
	Deny = privacy.Deny

	// Skip may be returned by rules to indicate that the policy
	// evaluation should continue to the next rule.
	Skip = privacy.Skip
)

// Allowf returns an formatted wrapped Allow decision.
func Allowf(format string, a ...interface{}) error {
	return fmt.Errorf(format+": %w", append(a, Allow)...)
}

// Denyf returns an formatted wrapped Deny decision.
func Denyf(format string, a ...interface{}) error {
	return fmt.Errorf(format+": %w", append(a, Deny)...)
}

// Skipf returns an formatted wrapped Skip decision.
func Skipf(format string, a ...interface{}) error {
	return fmt.Errorf(format+": %w", append(a, Skip)...)
}

// DecisionContext creates a new context from the given parent context with
// a policy decision attach to it.
func DecisionContext(parent context.Context, decision error) context.Context {
	return privacy.DecisionContext(parent, decision)
}

// DecisionFromContext retrieves the policy decision from the context.
func DecisionFromContext(ctx context.Context) (error, bool) {
	return privacy.DecisionFromContext(ctx)
}

type (
	// Policy groups query and mutation policies.
	Policy = privacy.Policy

	// QueryRule defines the interface deciding whether a
	// query is allowed and optionally modify it.
	QueryRule = privacy.QueryRule
	// QueryPolicy combines multiple query rules into a single policy.
	QueryPolicy = privacy.QueryPolicy

	// MutationRule defines the interface which decides whether a
	// mutation is allowed and optionally modifies it.
	MutationRule = privacy.MutationRule
	// MutationPolicy combines multiple mutation rules into a single policy.
	MutationPolicy = privacy.MutationPolicy
)

// QueryRuleFunc type is an adapter to allow the use of
// ordinary functions as query rules.
type QueryRuleFunc func(context.Context, ent.Query) error

// Eval returns f(ctx, q).
func (f QueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	return f(ctx, q)
}

// MutationRuleFunc type is an adapter which allows the use of
// ordinary functions as mutation rules.
type MutationRuleFunc func(context.Context, ent.Mutation) error

// EvalMutation returns f(ctx, m).
func (f MutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	return f(ctx, m)
}

// QueryMutationRule is an interface which groups query and mutation rules.
type QueryMutationRule interface {
	QueryRule
	MutationRule
}

// AlwaysAllowRule returns a rule that returns an allow decision.
func AlwaysAllowRule() QueryMutationRule {
	return fixedDecision{Allow}
}

// AlwaysDenyRule returns a rule that returns a deny decision.
func AlwaysDenyRule() QueryMutationRule {
	return fixedDecision{Deny}
}

type fixedDecision struct {
	decision error
}

func (f fixedDecision) EvalQuery(context.Context, ent.Query) error {
	return f.decision
}

func (f fixedDecision) EvalMutation(context.Context, ent.Mutation) error {
	return f.decision
}

type contextDecision struct {
	eval func(context.Context) error
}

// ContextQueryMutationRule creates a query/mutation rule from a context eval func.
func ContextQueryMutationRule(eval func(context.Context) error) QueryMutationRule {
	return contextDecision{eval}
}

func (c contextDecision) EvalQuery(ctx context.Context, _ ent.Query) error {
	return c.eval(ctx)
}

func (c contextDecision) EvalMutation(ctx context.Context, _ ent.Mutation) error {
	return c.eval(ctx)
}

// OnMutationOperation evaluates the given rule only on a given mutation operation.
func OnMutationOperation(rule MutationRule, op ent.Op) MutationRule {
	return MutationRuleFunc(func(ctx context.Context, m ent.Mutation) error {
		if m.Op().Is(op) {
			return rule.EvalMutation(ctx, m)
		}
		return Skip
	})
}

// DenyMutationOperationRule returns a rule denying specified mutation operation.
func DenyMutationOperationRule(op ent.Op) MutationRule {
	rule := MutationRuleFunc(func(_ context.Context, m ent.Mutation) error {
		return Denyf("ent/privacy: operation %s is not allowed", m.Op())
	})
	return OnMutationOperation(rule, op)
}

// The DetailQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type DetailQueryRuleFunc func(context.Context, *ent.DetailQuery) error

// EvalQuery return f(ctx, q).
func (f DetailQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.DetailQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.DetailQuery", q)
}

// The DetailMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type DetailMutationRuleFunc func(context.Context, *ent.DetailMutation) error

// EvalMutation calls f(ctx, m).
func (f DetailMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.DetailMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.DetailMutation", m)
}

// The GeneralQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type GeneralQueryRuleFunc func(context.Context, *ent.GeneralQuery) error

// EvalQuery return f(ctx, q).
func (f GeneralQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.GeneralQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.GeneralQuery", q)
}

// The GeneralMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type GeneralMutationRuleFunc func(context.Context, *ent.GeneralMutation) error

// EvalMutation calls f(ctx, m).
func (f GeneralMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.GeneralMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.GeneralMutation", m)
}

// The MiningProfitDetailQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type MiningProfitDetailQueryRuleFunc func(context.Context, *ent.MiningProfitDetailQuery) error

// EvalQuery return f(ctx, q).
func (f MiningProfitDetailQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.MiningProfitDetailQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.MiningProfitDetailQuery", q)
}

// The MiningProfitDetailMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type MiningProfitDetailMutationRuleFunc func(context.Context, *ent.MiningProfitDetailMutation) error

// EvalMutation calls f(ctx, m).
func (f MiningProfitDetailMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.MiningProfitDetailMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.MiningProfitDetailMutation", m)
}

// The MiningProfitGeneralQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type MiningProfitGeneralQueryRuleFunc func(context.Context, *ent.MiningProfitGeneralQuery) error

// EvalQuery return f(ctx, q).
func (f MiningProfitGeneralQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.MiningProfitGeneralQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.MiningProfitGeneralQuery", q)
}

// The MiningProfitGeneralMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type MiningProfitGeneralMutationRuleFunc func(context.Context, *ent.MiningProfitGeneralMutation) error

// EvalMutation calls f(ctx, m).
func (f MiningProfitGeneralMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.MiningProfitGeneralMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.MiningProfitGeneralMutation", m)
}

// The MiningProfitUnsoldQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type MiningProfitUnsoldQueryRuleFunc func(context.Context, *ent.MiningProfitUnsoldQuery) error

// EvalQuery return f(ctx, q).
func (f MiningProfitUnsoldQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.MiningProfitUnsoldQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.MiningProfitUnsoldQuery", q)
}

// The MiningProfitUnsoldMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type MiningProfitUnsoldMutationRuleFunc func(context.Context, *ent.MiningProfitUnsoldMutation) error

// EvalMutation calls f(ctx, m).
func (f MiningProfitUnsoldMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.MiningProfitUnsoldMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.MiningProfitUnsoldMutation", m)
}

// The ProfitQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type ProfitQueryRuleFunc func(context.Context, *ent.ProfitQuery) error

// EvalQuery return f(ctx, q).
func (f ProfitQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ProfitQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.ProfitQuery", q)
}

// The ProfitMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type ProfitMutationRuleFunc func(context.Context, *ent.ProfitMutation) error

// EvalMutation calls f(ctx, m).
func (f ProfitMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.ProfitMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.ProfitMutation", m)
}

// The WithdrawQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type WithdrawQueryRuleFunc func(context.Context, *ent.WithdrawQuery) error

// EvalQuery return f(ctx, q).
func (f WithdrawQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.WithdrawQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.WithdrawQuery", q)
}

// The WithdrawMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type WithdrawMutationRuleFunc func(context.Context, *ent.WithdrawMutation) error

// EvalMutation calls f(ctx, m).
func (f WithdrawMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.WithdrawMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.WithdrawMutation", m)
}

type (
	// Filter is the interface that wraps the Where function
	// for filtering nodes in queries and mutations.
	Filter interface {
		// Where applies a filter on the executed query/mutation.
		Where(entql.P)
	}

	// The FilterFunc type is an adapter that allows the use of ordinary
	// functions as filters for query and mutation types.
	FilterFunc func(context.Context, Filter) error
)

// EvalQuery calls f(ctx, q) if the query implements the Filter interface, otherwise it is denied.
func (f FilterFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	fr, err := queryFilter(q)
	if err != nil {
		return err
	}
	return f(ctx, fr)
}

// EvalMutation calls f(ctx, q) if the mutation implements the Filter interface, otherwise it is denied.
func (f FilterFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	fr, err := mutationFilter(m)
	if err != nil {
		return err
	}
	return f(ctx, fr)
}

var _ QueryMutationRule = FilterFunc(nil)

func queryFilter(q ent.Query) (Filter, error) {
	switch q := q.(type) {
	case *ent.DetailQuery:
		return q.Filter(), nil
	case *ent.GeneralQuery:
		return q.Filter(), nil
	case *ent.MiningProfitDetailQuery:
		return q.Filter(), nil
	case *ent.MiningProfitGeneralQuery:
		return q.Filter(), nil
	case *ent.MiningProfitUnsoldQuery:
		return q.Filter(), nil
	case *ent.ProfitQuery:
		return q.Filter(), nil
	case *ent.WithdrawQuery:
		return q.Filter(), nil
	default:
		return nil, Denyf("ent/privacy: unexpected query type %T for query filter", q)
	}
}

func mutationFilter(m ent.Mutation) (Filter, error) {
	switch m := m.(type) {
	case *ent.DetailMutation:
		return m.Filter(), nil
	case *ent.GeneralMutation:
		return m.Filter(), nil
	case *ent.MiningProfitDetailMutation:
		return m.Filter(), nil
	case *ent.MiningProfitGeneralMutation:
		return m.Filter(), nil
	case *ent.MiningProfitUnsoldMutation:
		return m.Filter(), nil
	case *ent.ProfitMutation:
		return m.Filter(), nil
	case *ent.WithdrawMutation:
		return m.Filter(), nil
	default:
		return nil, Denyf("ent/privacy: unexpected mutation type %T for mutation filter", m)
	}
}
