// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Detail is the predicate function for detail builders.
type Detail func(*sql.Selector)

// General is the predicate function for general builders.
type General func(*sql.Selector)

// MiningProfitDetail is the predicate function for miningprofitdetail builders.
type MiningProfitDetail func(*sql.Selector)

// MiningProfitGeneral is the predicate function for miningprofitgeneral builders.
type MiningProfitGeneral func(*sql.Selector)

// MiningProfitUnsold is the predicate function for miningprofitunsold builders.
type MiningProfitUnsold func(*sql.Selector)

// Profit is the predicate function for profit builders.
type Profit func(*sql.Selector)

// Withdraw is the predicate function for withdraw builders.
type Withdraw func(*sql.Selector)
